# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cluster
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres-cluster-secret
    template:
      data:
        username: "{{ .USERNAME }}"
        password: "{{ .PASSWORD }}"
  dataFrom:
    - extract:
        key: postgres
