apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: ${APP}-dbrole
  namespace: database
spec:
  cluster:
    name: postgres
    namespace: database
  name: ${APP}
  ensure: present
  login: true
  passwordSecret:
    name: ${APP}-pg
