# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-persons
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kanidm-persons-secret
    template:
      data:
        KANIDM_DISPLAYNAME: "{{ .DISPLAYNAME }}"
        KANIDM_EMAIL: "{{ .EMAIL }}"
        KANIDM_EMAIL2: "{{ .EMAIL2 }}"
        KANIDM_LEGALNAME: "{{ .LEGALNAME }}"
        KANIDM_USERNAME: "{{ .USERNAME }}"
  dataFrom:
    - extract:
        key: kanidm
