apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-pvc
spec:
  resources:
    requests:
      storage: ${APP_REQUEST}
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
