apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1mRo8c6IwPwjlvoxOcML75mXX5dGPJ4KlXEyOT63FfOPNIXG4/KHBbWxrsYzrRZ/qa4FU78=,iv:UQgqLl0aL/hty6Zu1kDwfqpwyqqtaO8yeIJ0PioAU6A=,tag:tA+66BaZeStWviWHc8VmjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFZlZjlTZjIv
        Q3k3eUpJVW84MDlqR252cFRzRzI3WUlWTWI0Y2pENkE3RGtOVTArNDdRdFRQd0ZB
        Z25JZE9TK2dSZnZjekErQVRKdWVWK01FU0lKYjlEWi8ramtkVEd5eHY0dld3LzJh
        c0Q0a3dncDl3QVlGV3dRcDZYMVBKOUtwUWFhN2xsaTBEMnMrTmQvQ0l2SGF4NnR0
        Y2RBdmdKaVpuRW52S29nVTlrM3k3d3NCMkozTExXN3lTSnJZOUI5ajlmdFl5VGVp
        VDBCZUFFaWt3MUxRUzd3Y3lET3ovd2JRZ2UvVmpkQllNbVBpVVJTZDl6RDJpMVM3
        NlBEUXJISjlTVTNrYXV3bW9vcG1qL0dKMmlrQTJGN0MvQVVpbEQ5L1BhTEdsdFZE
        ZWt2b3dMZHo5MEpkelJPVXRUbW9UM0VvMlRPNWV3OWRQNkg2WUJoTjJ4dnZEbkxh
        VjFCK0NjYUU3OTVVblFXYklCUjZtazV3K21xeUdoNHF2b2NUOEhCcGIwSkpDNFBj
        ZXVZNW9pK3N5ZHVTKzdiU1NlclZqMFRxVm5RYnpWUm1ZSEJTUndRbGk4MGFyWDJ4
        R2dSd0lsNG5Yb1FBYVFEYW9QTm1ia2s0cGhWcHRjM2ZWU25TNlpNOWM1VUdYeXZV
        TlNuVE1sbFpUaVg3NnN2Smc5ZGpGdFIzcEZXNU90RERwejZDaVdLcmU2KzRMeFVq
        TmsrRWF3VjJFN1BHMnVGaEg5QlZ6c0JEVDBFcmZzVlRBaER5M1l4ZEVvN2dxamJl
        WnZVcWJqQVNsNkd1SHhRTlVGNFVyUHhXaHpCWVFKa1FwY3Y4OEhLZU1aQVVkU0pa
        MHlOcGtuMW51cVlaT2xsSW5KdnhxNWVoNzduZ1FxSGdmc3dySGxaMmw5MTQ4QkFp
        dXIvNXErQ3Vlekd2eUNLMk5ndDJjRzRMM3pOTnFsaytxdm9TeTcxM1FJaTdIUzRr
        Uk16OXNMZjkzRFR4QzljS1VnWHN2UlN0bjVmODM1OXQwQ29NSmFqSTVNVGpYUm5Q
        SjAyU1o0UFN3WkRvMzhTQ0YvdENCajdQOHhCdmVOTXRxMHp0MXc1VWdmZkxhQ29o
        MmxkeHNYbTFDYUFPcE1TVWN3UHErNG5QOGFMMitQbDFMWG0wY0tJZGJtYWZGNnVD
        R0lqSC84YUtnRWhwQ3BiMW9nRzA2QnlIWXduUFMrTzlBbnVUcWtOR2xQbUpRWDFz
        aUhnQmVZMlp5SlZUK05JYVQ2TnhpSmRzZU90L2tZMnA1QlkzbWtBejZST2RoSy9W
        WkdNaG9MN244bFpPTWtmbEREZ1dKVGo0VjFQVHV1ZGxEc3pKZDBKb2IyNTVmM2lw
        LzFOcXVuVkZJUXlJMU5XN0JVL3YwZGxDZGhON3lONldpNmRaYVJGSnpnOXBTaGt2
        bGFRQ1BCczh0MUhOOTUwVWFmQ2xnM1J4ZG9ycHcwWS91Rm5kRzZlTGQxS1I0UkZs
        QWpIdFVEdzcyQ2hQOEVuS1NpNWk5UG44UlYrUGt1RHVSdjM3M0tTWDJoS2dkazZh
        d0d5V3hCVmc4TzkvQkh6eUo3cnByV2QxM0ZPZms3aGVrZTFDdkdTdTAzaWVOVjQr
        NG9POWRsbnRNQUtsNEx2VDBmajBYR3o3ZUw4V2RSNVNmRk1tTXFLSFZIM0UvR0Ev
        bjVkL29SdUdwVHV2SW1DYncwVmR3RkxZSnBvOExTZlNnWVFNZXNXaHY0aHFKeGh0
        NWlkTUlVUU9GQUl4UmRvbGE3ZFQ0aml1YURVQjVVKzF3ZVFyRU1XaCtQZGM5TjBC
        clczTS9pTU9PaXEyQWNiWkUwT3k1VVg4dmFmMVRVQ3V3d0l6a08yN1d5N1RSNlFp
        OWs0dWtsUFRZcFVyaFhOb2hldFBUWnJNcTYrODVPaHJhWWhFVHozUURYSkZnMG9U
        ck5nb3hwT3hRZDdkQWx0K1RxcmhiZHNzblBkdm4xZm5BUkdGWUdKQ2V6Y1RTQQpR
        ZGpzaDFZU1QwOU9HTFlhTzFFd25aQkw5N1FZNWdKVzAxQU5IWWZBWklBCi0tLSBo
        a05KcGFidXV0Mmt3L1QycU1kVU9sM2M5cVRZWGtBWGxsNVdDbE9jb0JFChMWyUiW
        QP+w8F2FMs9wlsWNAW1zwZpUe1y+j/TG484nazoXyuJ/rKOkhdKaSmpUuAnrblfQ
        V911HjcIY7zyd24=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T02:34:48Z"
  mac: ENC[AES256_GCM,data:4rKOT1Fiht0kY2KGFEaegvH/mKceHFuxRC0CejOumbfFgqkOS7etHme1of2FPeX2tpw4JdfaeGSOM2sok75K/Jh69DRwfugPJqTklhTR/oLfSR+VFIGUqn80/BATg16p4/CjseeTk6Rm2fpbkxCUGnHX9apnxzjrJnycdWOhCM8=,iv:4vrHJOM8edZhoYan40VaDA41TqIGWZCXC4AHq9GI32A=,tag:DncjlPiwmi2u2dHliUYyJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
