apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:MwHkHXyKhLl96MFMMYOfueGW1oQaDrZ3a5dY+sYmIJ+1qtZLeWJFgZXEmnKWOKM4n73ZNSs=,iv:ZLkdLOGOp/aW2JXURWFQlnkOQHcnumudZ6QK/Zbn2Qg=,tag:/oSF4x6bvaqz6MK22dnTQA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDN6Qm9mekJW
        cTBuMXFnNE45WGxzL0RpTVlEWCs0amRZUkprdTZMa084ajdMNmJBUmZVMEN6REdY
        Sko5Z1NSOThmMFlQKy9DbURoUGpPYWdhM2ZJZGR0KzFEazUvelg0Q1o3QlpVdXZW
        UUx0MkJEc3pvUXdPVVZwWGJ5TWptc3hNWUdrWVpIRkhsRHI0UlZJQmlsditSL1ZP
        ZFMxaFdYUXkralJEL00rb0hNNzdvSU0xTlhWVmJKU0VwRGwzbDF3aFBNNUhWZG1i
        U3VST3V3akd4R0ZmNFIraEFqU1lwY1NyV0hJbDMyMTlRY29YS0tmOE5SYjhzTE1n
        V0FvVzhnMlpkRXRFb0pWQzJOU2FlM3lVa1ZaaStoWGRZNDBhSUdvMVpoK1c0U0N6
        bjdVV3M4UmtDSCtsRFAxbm1NeURQQ0Z4c01CamN0clhMY1ZRUXhpMDhyTm9ublFJ
        dTYvUDRCZnRMZnI1UnNWT2s1M1lhSU11Yllkc1ZrbS9zRmpzMm84bnBHcnVoOHNw
        Y05CUEMzVDdETzZSUlJrY1Qwc1ViUlM5SzA0QzRUdkVuVnVPT2x0eGYxc25HbFAr
        dHplOGhWTlVhZlV6dGtlYlg2dzVZSWU4VG83anpHdGRDQ0s1MEorNXNvTUdWY0lG
        SEU4SHFpbGxTQmY3b2dmVHkxd0Yyc2FWZG5LeEwxNlBZcFFNbU1vVTVyc1oxbTA5
        RUdNTkRFc21vSkczeWZ2c3p2Z0xGaVpoTkJNcERuWXBpazdGOFVSaFFuRWJXTklT
        RXVSZmU4aThXSlhrTGp4Ukd0eWdwYmF0VUhJbEt6clVOT2N2KzBxME51MzhWa0Ir
        cjNLUmhaTlBYbDM4ODR2eFZGVFdoMzU1Wk5Lb2oxMklsQ3JuMU1UV1c2cXFvTGVS
        ZkFKcGVaTU44bExYdFJZdTlKSWh2WVNFbG05WVEwZnFzSlZReWQ4anhJd3NJRkJJ
        TzRWbWJqUlNvU1FUN0F3bjlHVW9ya1hLano0SDNIRGtyc1N5ZVRSdEE5L25OandG
        OEprTmlxUHR4M2ZWb3htRStEQTNpRXVubUpZeTlLYWUydWZaeG1VWENIeHFSS2w4
        SjhMVmJLdGoxOW0yb2s4bFhTN0Q5SGl4K25QY3NlODlvdlF2TURsMEk5YlRkT2tJ
        SGFwa1lHNjZGZ2kwSGlrT01hYU04N0d0QnJ2SiszV2hqSGVXWUJ2M1hTMDVLSW9m
        eVVkWTdDaWdyWVYraU9SNmJLTStMTnNBcEpiNnBFamJ2dzRMTVBMVFB4NGdMS3JV
        WldNYUJLSzFKQkF0UUpOL0NtTjNGNk90ZTY3WGlYYm5ZZEZpa0F0TzIvUldxL0R0
        NHcxaGxPK21IbjlnTGd5a1F4SXBOckp2TG5OUDF6Wk5zZnJid0Zwb1Z1MHN0NjNJ
        Y005VU9xSEZiRk5MYis0NDJNMnlSdjRqQk4vV0tTbnBpT0hNbWErY0tVN3ZiRSt4
        Vmw5Q1laNUdNSWsyLzN0MnV4U1RSTVhvQzBFME5CcWVMamxNL2NqU3JtejFOU3Q4
        K1FiRXFEWk1wRHdYUEdIaWxGNktMTXZxRVBER05GYnJWTlZ1UktQQUVDSDNaZGg2
        TC94cjRTa0R3MnRiZ1ZtV09yN1pDQXJDdmEwVElYakhweHN0MHBhTUJyUk1aYVpF
        S0p0RGtHbE1NNFRmUGVqcmRiK1Z4L0xyL2dVbkxoTHlmK0J2TkI3bmovTVBFU3Ja
        SjFIOFBkeDkvck9KVkJpdkJQMndac1R3R2hWT2tFS01GM2JCRDRNeUdlMkNLWW4r
        Z29tNytiMTdPaE5USGdqZ0pmdStzLzBsLzk3YzF2YVFiWS9PanlIS2JIRUtreWhW
        MXV0K2dGTitERjB2ZjNyYmRialM3Q3FuZFlKSC9NazdBMDFBYjEvV214NzIzaytH
        MlV0TWJQSDR4R0xTVW50VnRvVGlFMExmSWRXeGNPTnc0Q1NYdHUrUTV1bkxGUQpy
        YUdRYXRpeTByNjQrQ09ETDZ2K0NjbmFPbUxqR0VqaXdnU3R3WmRhLzVBCi0tLSBn
        QmFSeWxzUjJreDB0Nnp0eFpIQUc0dy9NTWFDRHdnWjR0NGNIODZNeW1JCqKwyo0G
        z+GYsXZ3nJGsfElxHrzFplQ0+BGlVop2Wh2DwevWiT5MxtdsFWCO2YZJgF2eKoG6
        v3BiKAXaeucmB3Y=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T00:49:57Z"
  mac: ENC[AES256_GCM,data:O1OJ6RUdUDnwHe0sQGt/jtLI0mc6B/3dJqkKbXDlpIpT2RnaLMVDr8gUDo0KPjIbyql0OuuecGHGuvYyC0efh7CgtedwwMzLaWpvQR9gilgQuM85EcElLhswQ9Lt3gyanBGZoXK+umqz4KIpS7EDyu+tv36TmxXXJHthGW3ZoLA=,iv:PGrF2jcO/a4Cfog91Lu5GtHNIhfUS6YFAnPxWI8qxLU=,tag:zsCEgMZzur8UGvyKlBRawA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
