apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:6DULW4ajajhIrQ/G8jReVsKk5hepY+UDQQK4bIK1qKDfTEixmeM4kUs4oPhxDgRqLpQzjlM=,iv:uGDimUGnPWcPY/6y8TuoEF0KraME7+WQRPcbhA4t8eQ=,tag:8J1Jhpzk7QpO1Hm+/l9DzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFV1TTRhb1dZ
        N2pia1RyQTJNRWp6SXBlZEkvUGVGL0NGMy9SMFVIWThYdGtENGhkemZCRTRxdy85
        cEpUSWFaSXJ4aXpZd0VZbmt4bHlFTHlpeWhUd1Z6RGFGQlE5Z0tFU09rRXFuR0E3
        clVpVUJXeU9SYXVHRWZjQVF3ZXRtaElIT2JUQ3J3eFhCYjhmaVp3U0lldHoxbjhw
        YUJkditkQ2RTaXUxQm9ZTjNmeXJWcXN0dkpaM05wNnR0M1V3Q0ZCd1VjNk5QTUVK
        VGRKMmxWMXErcS91c05iendRcURvOGdMTmt3TzNncU00dkRPTnZ6VHFKSWpkYmZW
        U3A2d2lDT1ZmcVpQblFFRDQxd3VmTERqeDFKNHd0VklVL3ozbVdJRnY5UWt0TzB0
        WE82ejlRWWZ4MFB4VTNlU0VjUCtqcjhIUkxGcHhiMmN0c1JDcTdlSUFER2ZqeWIw
        ZnMzN2RNSUVhTkVqOWdRSVhWR0RaRDhqU1ZVQmF5SjFud0ZKUXdJZjNDY0FpdGY3
        TGFpbTJrVUJVcDcxTTAvaXNmRDNoaWRGbXpCTjVPK250OGZ2cWhDTzhKYzhDT3du
        U2lOa2RJK3dJamNXYmtTeWZnaEt2em0xYTJBK2hEYXcvNkl3YW1ManRvcXg5YWlG
        NCthcDdRVVZNak1WVWxxMzV0ZnYzazJoREhPTUNaQjQvR2JQeDYrc3VUQkFPM09T
        YTdyejRsRy9vY3BZMUJ2dE11SWVNNjhrZFlPM2QxVVAwZzdOSi95VmpnVE4xd3Ex
        U1ZoUjdBZXIvWjhUY1lZT056R1hqb3RJcEVOM1JRYlVXM0VVOG1HaERPSE5iLzM0
        Z0JEdzI5ZEp4RHY0Z2hGM3JjcmsxVUlxbnJnSENnVmQzZWk1OXVXTnhnU1FDak92
        VVB1aEdSUG9PV3F6QWdxV0tpdzJhZWM0WC9aSjlXZFRYUDVpd2JRZXlNKytwNGEv
        TzBaZzFGVUdXWlpXWFNCSU9iRE52SXA1cW5abU1zTGRxbUNKWWx6aW9KbXRFdzM3
        N1B3UVRjaWh1KzhQYUExTldjb2pDcE90YjMybUpCUWxvZDU1bHZGZ2sxMGE4eTI1
        VHpvL0hwTS9Nc1JTVlVSbzlmWWdlWE9Rb1V4NUNxV3U1UWpYQVA4aHZ1djRHNERR
        VTV0b2ZySlBFMTNzdTNQVDU0QXllMVlTZERUMWxILzdLd083UVFvZE94bXlmNFhS
        a0MzZlEwdEhWaHFBUjZBSDRneGgvZVJROUd5VmhFNm5xc3RaK3ZUVU5pc1Zqc1dz
        WWI4MDhpendJOFBBUEptOGNnTUo1VEVWWnVyOVVyRmVNRVJwQVQ0c1luMDcvNHYy
        dVZWKytXdXR6Q1NhdDJhTWNBb1gyOXFGejBUOGU3ZlFnMVk4dW50enFHOTQvenZJ
        TllWaEpoVGYxakVaL3BkbEFlUUlKSWVlTHpHWk95c0JCMjRNdjVNZGZFdmdWbTJQ
        Q2xmYnFHNm5ldWFyYVVJeVhHei96SEtROEs3ZUV2NHRLdy9OV0E1NXU0SkptWUh6
        akNXZ00rdjdXQkVRVUhjdjNsd2xCVGlYbzM3RDBkT043dVZ3UFJaNWdGZENlNWZU
        NlovTVJSblJoazFDTVNzeEwrWXNMU2J2d2tmM1hlN05wK3BVYUVsdFhKVmNsZEtF
        eDlrV1BVRlQ0d0d6ejNSQWxQNkRkQVFCTUpRWlUvdC9NcWpLaG9WZk54R1dianh3
        enduTStyUnhJck5FWm55eWtFb1pvbEhPUlJ1NmVucFpwN2gvdVNTbWVkNDB4dEt2
        VUw4RVk2aXE2ZzdnbkF5ekprQ0YwWEZmVjdxaWxnVUxsUVc1eWdMeVo4OTcyQldt
        YTR0OHBZSElqZDYzSFNhNGZUR0lBU2V3d0YwWVpNSXdCYm5hSEVyS0RlaVRKK2Uz
        ZjdWSW85aDFoUFVjUlozaUZtbm1RT0w2TWlwSnp1NFd5NU5wdXlEcDlsSlFXQQpM
        Y1N2WXFMdmJvWTBqUGV0Ly9NWVJTQndLZWJpeS82L3BkQU45bGIrd1BzCi0tLSBW
        QUFBWHJHOUFNNWlHYmM4Wk1sY0JUWUZHaS9xQUdGb0VlWUlxZzgvbjRnCjhdHgyy
        kP4+RJcPlrMazcd50ZwhoEF7823RKP8gO0i3WMS86eI7ySITvuklXBK1Yay5jmVd
        GsPl6auuv/baRj4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T00:03:05Z"
  mac: ENC[AES256_GCM,data:F3PtJDEgH8myb0dUGRvWT38kxIHhLYmpMKffkfWpkZYBpLC8Zcow2+k15vlf1UokylHu27cYoNOTuYcsbP3Fi7bM7Dww/JXp7Cq65S1KaHYs/p9SdfovsHGv4sI6bJIOqduvc8mNRpjAdeNfMoVhAEIPceyt/jP15Kn3YWVLnOc=,iv:mu9nq0tqkjQCpAKj7a8z3qeXW0tLNmX2HNu2B/tbGhI=,tag:Xfh5Cb/Y3xtH0Z+FhQCagg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
