---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/miroir.home-operations.com/miroirnodegroup_v1alpha1.json
apiVersion: miroir.home-operations.com/v1alpha1
kind: MiroirNodeGroup
metadata:
  name: std
spec:
  nodeSelector:
    matchLabels:
      storage.mirior.home-operations.com/class: std
  template:
    pools:
      - name: default
        lvmthin:
          device: /dev/disk/by-partlabel/r-mirror
