apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vjdKv4ZQQ5TEPQAD,iv:VEcQljya+ou/OG74BDb1QbVHI5ioUUFRKfGAePgHRqw=,tag:CXINpA6HH0rNzdClg96v/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC9BYjYxenZq
        d3diTFRZSW02N3NUR2ZDQnNvWjRUMElDdVdFaXpkM3J3NDZKZ1U4cnZXZTJkSW1Y
        NUlkYlVlYVRRczZzNEFkMnYyS2NWV2RmdFl3VEVPWHNDTTFrVUJybTJHTXJlSUV6
        VGZLR1VBYWNCaVpuSU5PckNKSERDbHprSXZEb0w0a0l2OGQ3UG04S3RjTHFrL1JV
        MGtGUzR3L2Nib3dvbWhvVDM4VVlNUzA1N1JnRkc3Zk9xZ01PZmFpU3ByOHloVGs1
        OVVVSmRHMHZyMzJOdmpFNEhCUUE5NGpkbytWaGVGblV5WXJ4YmpmYlc2L085eDJT
        RGdrZ1VFeXRua0VFdXUxcWk1RXJiL04zWkp4dVlkalgxSGxYc2ZuUEdXT1liVGxB
        NTVmMnh2K2xXbUd3MVFqcGhxUGZTK0ZNMnZJdG51TWE4cjYrNlV3QXBCYm8yRkJK
        ZW5lTS9TaEpjTzA4Q3Q2MG9lK2M0WEtWcFVQMEQrQndzMUM4TTg5NVZCOStJMmJS
        MHJIVVFmWGNDUUlZRk0waWF5clJoYzRaRUl3VUtHd2tWdnl6VksrWnFBTVYrU1Yx
        ZmhoUnU5blhYb2gwcEwxbXF3SjlUWlQyajBZYlgyZjE4d2NQSW5LWGVqVXJMTzZP
        elQ5cCtkZlR4anVjMmZ6OXRVRmJpZjlCcXIyWUkzN3RFN3QzcUYxMlFrMHgyd0s4
        TFFQQXR1TFNjOThYYkgydUl3aVZERWVodXR0d2pmUkNYUTFFa3FSbDNkaFlGQllr
        SXZyRHlUbCtjeVNDOTlFL3ZKYjZHcy9WYUNDcEVXQkMwTVRBZUhLRktSTkEwbFVi
        SnhoV0x5MlQ2elpoR1NWd3hUVzJCVTZwcnhnL2kyM2Q3d1VLZWluQUJnWVZEeUZo
        YUpCc3oxQXc5emlpdWJBNVJNSnE0dW9xaGVPd0Z0RTVreXBFYThnUlBDUXo5amZa
        T0EyK3YweitLZFFBdlhVS0tPaWw5bnBUVUlIRTVxTUZJUjE5Y2s0cEdZdWxPeE9H
        RHNlNFk0cXo5d0VmNTdMTWZtR0ZyOXU1MzQzU0xCMldQcVpFSlNHdzF0UW9MNUcw
        bVRMZnMvT3VhV2RPMUJNYXk2WEliVEdxa3I5alBZNzR5TXJoeFZDR0p2RWNUNkx5
        VHYvUEQ2UFVqS1hqTVBQUm5yL25lSzdLYUFpOUp6YzhHRlZVa3J4amViaXhqelFM
        RGd4Ymk5S3dzbGJUWVk4NDd6U1FaWDIrcmNPamdpcVJLS3ZYSFpJV3NHOVlsN2xi
        VjUwUkhqM0owVkRDbm1UUUQyMWR5ak5pM3JtcFlLenVDOWlaVW1zUktSdG11cXpr
        eEZ6ODNZYjMxZWExekRCNnBhTWxQWEc0Z2Q0bmxJb1dDcjRLM1hUVWlpd3dUck1z
        c1RDN2pCenRrR1h4RjExQkRCc1EwbmxESlhTMnlnVjZZaUNWK2tjRDRHZm1LNDhL
        aG1XK0Q4Ny9YZ3hjT2xVUzc5REx1OXNpVFZtaExrK0dMcFR4R0dKZXJIbkp4bENW
        VkdvY0pZc0NTaHhKOEd3NzJYK3MyMlp2OVVFclIwM0xya1MyR0JMdGFtZ3owb0o1
        cVgxbmZhOXl4Uis1bGJhZTFRZTdRZHc3RXhEcG43ZUZkWDJzRGlsTlZXaHh5VllG
        T3JId25MY2RDd2txNzdHamtPV2g1V0ZXL3VxMXE1aTNJRDVjdmpId0hpd1d0VC96
        MDNDc2MyNHVwZmdxVVdxdVFwNHNzaXFid256OWxMZ3ExOE9Vbk96aW9aWEdwZ3di
        RCtSTnVYWHRPVzVvc09BWlZHT3hmOGk0UENUSXg5YmY5UFhHdERldDFhcCtrSy9p
        azJNK3VpNG52WXIxcXpxcG00VHlhWnM2RnVJcjhTM09JVDRmUk81VWZmSWt2cVlZ
        T2wxbG5UM0o2M1BjM2p1eFBCVDBJQnpHQStBZGZiUU9iKzFpcEpqVFF4eklCZwpV
        SDNhR3pzemZ1REZkYkIyTEVjdzByWUE0TWZGbW1YR2NEdUNDY1gwWXBzCi0tLSBR
        eFpOM1ZrK3B6dUhQK2lpeGVZbytxRVpWMHI3QUM2c3lSckRKQ05oeC9VCgYoydEc
        OJ3aVJZhDc3DcKqq9rWFXVq3yvabIfwlOYk6RA2/X3V8r3AyqXfitRqHp0in/KKM
        0a1sXpJT7TgOIO4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T00:12:07Z"
  mac: ENC[AES256_GCM,data:leD4I5wYfSvoB8nWj2SyZsy7r+pNETVAFaoo/1I8gYI3IY3fmxx2OfL1QMvbQkroBZd/3hfyQOuY1rBI/UB/2Z7mQpI1PHQUl8kXxVWeNFBnkLelXXSxzGD0uyH3x8pRCLjxaAE+f2RotwV7R5Ncs5DyKdlxFmUYMqhDj9QAUfU=,iv:w3o7zP93QBDcSbxFPb+wlm/h0RJl5sOYwWknm+tcwkI=,tag:T5lr1kakfAJjyhNc00UTdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
