apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rBEOGlp+bkBBzEVw,iv:jcW3tk93oPF0FoCYaMBcSREQQIB28r1iD3ned8o5tuk=,tag:f4wqcG5CG0Jm5OLEEKH5Rg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9KYnRqUGNt
        ZmhvSS9mM2VTbmhUdThPZlo2NjVkdjBscGM4di8ydW5qVGJDZFVvV0Foa3BISkd2
        NzdML2hsdk1nbjhYNWMyQlFENTFHc3dSVnUvY09nU2hwdXBRdTBjYmRIZXI0enZI
        N1VrUXdmd3M3RlM2TUFhZGdlSlVxNWVTSnkzM0lhbUVYc2l4a094OU5YTjdhRVNu
        RmNkR084Y0Y4TnVvNVFQUlZjS0dRUFRycDRibVV2ZXRnZnZkU25mNHdIRkNJVHVN
        MmMybCtzUkJBWW5Sb3BiT3FHT0dkQlplU2gwd0VmVEI1UThjOGVSck1nRGJDeGQ4
        bjBWVkl1eDBlcVpUUDlPUlg4SHM2aGVQRDkwZ1hjV2JSZmJEVDN3SkpoUzJXWlFx
        U2hyU0xvRGltTVlNVnBKd1N2MDhMejVyYk9qT2QraWd5UzFZR1VhS0JmVlNVeEJE
        ajV0MnZHRUhHN0doMThrcU81TVA3ZDdUUVRIOS9BY2h2akJGczBudTBZQzVzMHVi
        OVExM29JZ1RkbzNHUTM1bDh5WUNIOCt2b09iT3gwd01JT3FIRW1hN0dPNWNDZlhs
        RzhSVUxOckdhNFRxK3lNSUEvY29RMkI2b0dtRkNhSjIraHFTZlMrRjBhUEtNeGx0
        dlphQ1pKVGRKOEtLVGZJYlVPS3NXL0ZPQ01oVkphcHdOYXgyY09vcWlNTHkxeUhh
        YmtLeUdMd1JWL3dFdjdoUktZMVdBa21tN24xUzZ3ZG1tamJBaU9Xb3lDT1FLRE5X
        czZGRzNVTlpKZE9YT0x1WUdacHpzVmh3SU45eFJNWEE2QnlORjRyQjZRcnBVTGw3
        ZGpCN2VEc05DNlZKVGFUNG5EZzUxd2Njb2F4UlUyTGlmOStEeFZiWEF2YkU2WDVL
        bW9UK3NoSmxnWVNLbkJtUzJlS3ZWd3NWUnBSUjZGNUljcSt1bXp0VDdUZ3p4U21r
        VU1uaGt3S1c2Vlp6VjVBVjVka3JvWGJybnhHVG81a2t3b29UcXZpK0UxVE04ZDl2
        bWlFQkphbGlGbjFOaEpmN3FUMThUdzE5bU9tajJVdUp0aVd0d3puMDh2ZDRBcDdD
        RUxOSWZGcFphQnI1WWJiQkN5L0Ezam11OXFBQzRzOTdiWE1ONHorTGZ0aWtzV0FY
        Rm9sUFM0dGpINmdSaG4ycVRvNklCRml5YkNFR3ZFUThhUCtuVGE0c1NaTFh1TWJJ
        VmtTSnY3NUg1UnpxdHBKWS9JckQ2RTA0T2ZYV1FaOVl2R1JaNWJWeHVWaThkWDVR
        K2tHazY2U0N6Uk9XYTh1eEY0aTRkc0lHZ0U0V09GWkFTL016a0ppTDExMTBGNVM0
        Y0VLZ1FpTU5FZktXREdPNEVMaWlKdGRodTlTaDZBSlpGb01KajRyTURwcGRNNGg3
        MXltQ3oxNzJXWGlBSDQ3a2hQcE9QSUJvK1RVYUJGOHpWMWtleEsyNHdBeWNXUytx
        ZlZZby91aGRkbGZFSHBKMDAxNkZBV3RVa0FqT1dCYldTTGhhUlZ1c3ZXYjhUOXNI
        bWFjMWEzL1hILzlFeE5Pamh0VkpnVllPdWRLdUgyZ243Qk5LUkppZjN3MWpsM0pM
        aGtDK25uWlZoVlVwa1lscUlGazRCU3RyODFYVU5haHA3M3Jsa1FoSHU2enJwZHFj
        emYwcXdtRzZRekF4NSsrWHZnMEIrRU05Y2FWNjJDTkJDc2FSeXdhb1h0TWFVZlpZ
        djFZeXZoczdwekoxd1F6QjN1R3lXS0pIWHFEVnI0eWtNekRWeHBzVUFWRm1Uc1lX
        UXVyRjVuQTdkbVE1bUdSRXVmK3h2TFNYeWpUTklVc3lBc2lHMmdRQmxsN2dYcmw5
        QldobXNBbFF6ZWpnZmZ1UUpMNVo0SHJpclhpOW9keGNoNUhmKzc4WFJaNnVhcWFY
        WE9ZS1pqZjhIcTlTZ09udUJNb1NacDVWQnJKemkvbzJudTc1UnR3aXh3S2NBUQpq
        T0d2UUQ5QjBXZ3FZazJ3dW1jNFhTclZvWGxVTnZ3dnFYMVJpd2t0aENFCi0tLSAz
        cTQ3cHQ1UE1mQ0N4eVpIQ2VJeGoxS1hYbHlTbkxCWlMyZDdPUXBxK1VrCgf4/BMY
        QB5gfYha4prtcXq+PGhrVWqbFLNehy43VCOQVVmAgrVcVjI47KrzKYqnYtZbZz7d
        EhGige9qJOnpNSE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T02:34:48Z"
  mac: ENC[AES256_GCM,data:TBKFOiDo/FnCvjQATW/YxKzxUMwD+PtOe4Y9noK8ga3Qx1lppRlm2jxMGImxRqH04pzzuRejurI2pncb4zlvDNFyaw9pe7cFdOA34KQ/5OQ4ceN3vswpjOIrC3e8LqRvucZaTmw16TzNUe/pJiGYs6HVZPDXqVjU6Zdf9aYumeQ=,iv:pixw1TxpZpi+jA7xGv5lNQ707EW6gNAQgwOv05EgZm4=,tag:duvDL1ahTyPdR55pU+LRYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
