apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:7ooqsIodwhst7Pz/,iv:hM6rEN2HyFXw4G/6IPbaMpDd05yDTDd5EJB0HD/2haY=,tag:7iekdw9/k+l3XwNdIgp1Vg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEg0SXlrN1Ay
        Z1dUd3JqUjZ2NmwzdWQ0QUNId3FidkxneDhLSjIrM2VVaThQb1Z3dWpJOGdCUWNM
        OUJnSm5WeFdKc2E0ZjQ4L0VoMis2WDNQV1ZnalZ2NjI2a0taTnVNRHdRa1FPNHV5
        UnRJVDE5cTBFaTRTNlNKL1FRbEk0bWszaTFsUzdmTi9iYzRMK0ZUYmI5MUVPY2Rj
        ZXVyaXRsb1dCcUVJcG0rSWdWbWo1ek9MSVdvWEhQSjVxcjhYR2lCd0pObEk1dW9y
        OXloSVlWbUhlTWZVSjRzSjErOXJQeU9QSExvbVBhSEJzcWVwYjRPRE9iVEEzUHZT
        TFFSTTJ5KzI1L1JTdG5zMG41bjZ6TGRDWGlRdityVDZPKzFDN1hsSEx1dXZsTjV2
        TFAzV2pQaytLK20xWmlyczZ3RFRCUjN1dkFIdHlrYjhZYzRHZURXQTIzVTJrcnlo
        Z2ZvYzZOWlhWYXg3L2xsVHBHS01EdG42SXpYMUhmKzFkY2NUVmtDdXE5cEVZcTBj
        QXk5NFhVNUQxSXBTQ1RCYzZmWXBKaXJlbjA1bENOVU1yQUZHU0p3TGQ2WEtWdDhp
        djJpR1g0eCtUQUhCNndjQUVkbWdzcU9TZDE5Nno5ckwxUDk2SHRGNmxGM205RDls
        S2JMT1UrYWx2djM5a0hZaFFYaTdNYXdjMlpMVXE2QzI0NkxBY21LNUdEVWRVWlpB
        MCtyeUNpVm0zSkgrZjc3UjNpbStHMVlSaXNNaENNeC90NlIwWW4zNENWNGR6cyth
        WEZHc0hjNGg0cFlnZGdLNGJsWFYzbnJDOFpkaExSREdxTHNIMWI0NC9Sc3Y4TllJ
        NE5NNmM3ZWZLNzBFdEtZaWNaZEZXNjBCa2w3azc4YUltaFRsbFJIMWtrVEtzRUsx
        NHVjNDFkSUFqZmhvT3diZXkxV1BRZjZYN0xJUlFpQVY4ZVZZZDQ4VDRoTXFCb0E5
        ZWpKSy9jQWsrZVlxZllTWVc4WGRZVlhsQyt4ckZoL1lDSlZEQmY1TDlxMUNRaldl
        REdLOUNPWmFvTWZtTkltUy9QR0Rqdlp0dU1ycHhOR1ZoU0pxeUxJSEphSTdnNnMr
        WWhiWDlMWXNubmYrcHVhMDRtUDBaZFhZR2QvSEdkbkhETHdTZVJPbzNlSVhLQm5z
        b2J1RzZULzdZc29nUjlVUlN3eGtKYXNabnFmayt3amJLZDN2aHFOUDUxUGY2M0pk
        enJpZnJ6eHRYYXVoRUpBMFI2T2syMXNSUzY3b0lyMEhvOTlkR05XM1hFcXhHMDIw
        YzdabERRUHJTbUJlamZJS2d1L1hTWHdxSHpyYjd3SEczM3VDSlJ2VEVacU5TN0NB
        ODFKNjdUQmlFcGw0RU5xUzVITW9rVUlEcjJ3alBGNEZYdithZWV1T0Z1dTdrZ241
        WmhuamFNUkxjSUlDYVp6L2RJN1JTYVlPd0lueEhSQURRYWVwbVk3SUpha3dkcUNI
        aGUwMTFXLzByV1FLNmJkNkhsWEFpWFZTeTZ2MGJkWmlQdGRJWi9zcEZVUk4vUWZy
        bXBUVUpnZk5GY2VPVWRyRGVQeENYV2ZuY1VQbjAxcERzMHAzeHRHTG1qR1dsMnpr
        bldqcThsdE9xYmNocXd4YlROck5HTG9vSGpLNVh6WDl0VFNmNUk1MldGd0dlSWRx
        NzEzNFhiRExJMzd3b3N1Z2NRSVh3MFpYNERoL1U0dEFZaDZLQ1JyNndoeEJQYjhQ
        SGRSeUVqMVpOd3ZaeFlSbFUzMVFqcWZmS3F3WWdQVlhzRFZtdVBvdEtqb0xINk5N
        MElkUWY4c3UzUDd0cTU5NWduYXV6THZLeUxWM25PUThoVlZ3QlZUZ0g5VzZDSExY
        SFN1NFpQbFA4eVpQNERTY0I5UlQ4aTRvS0RZdURlTUppREdoVmthMXhTRHV5WEZt
        eldZam9UYW5JaE9Nc3l4bXdwNjh5OEU1WERxbWJwSnp4ZUNxODFaeHJUZXVjUQpm
        Sm84blB0S0Z5WVBreGM0Ui9UYUtlMDNDOUI5bUtKNE0wOUxmRWxObFZvCi0tLSAr
        dG5lOHpFR1RvYlVmUzA4bzI2TzRHR0RtcmNVVXZ2NHhiWXpFUUg0NGVRCpfFz7Xk
        RJtTbnX9XAhSqf5nEIjk6XLrseAPC9GZLROYOuzxyfxyW7qbhnfvFwDwUU00svLa
        JJEq8IroaKd/AkQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T02:07:07Z"
  mac: ENC[AES256_GCM,data:CCxMv6dH25qGivPLn9aXOKdzUGGl9i6NMq5yLnRMlz0zsR80Uufc2I8+TTmWxH7JoDFqsNHxQfdtHk75tMZgYdScunlTiZW5i2Zppj3HIMxSdRhB8yYCxt1tqgRW+tco/oVOYRtr2XZ2Mt/Tdgn3Zti1VsWsobALJfHzr/rJ4D8=,iv:y0lIItolC9D4eTrUb4nyP2uFiKAVKc4QjvVZbADe7/E=,tag:khxuP2PH/RLbOAygJbNQGg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
