apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:GwP5QwgB/hY5ym8Vwe9B+uKDu2uGFL2a3hfPV/5Tqlg=,iv:WLcEirDoMHll4mby4+Bza0aNyIcwmEbvxWv0PpmrGZI=,tag:8OUNnMayrs0hOdCdMqIhPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHppNHl4a3p2
        MVQ4TWY3Yk5GUkFzUXdjSWNVUTRETVNzOFRia0trQytNZDcwdXlsclVaYnRROGEr
        bWw0eDRkWFVrWUVuME9MZG5IbXF4WnlTWVQ5OFFkelJ5aUkvR2k1aGppM1VZZG1z
        TXJPeGpmMnplc0ZzdXN3NmdCRHUzZ2tsalNEY2E2bXRNZnpDcFhBVkUxMktQZFRy
        UGJham9BUzJNMWFTc0lXVEFGV2kwRnpwcWlkb2dzV202ZW12MXVzU09uU3ZLbURF
        S1ZPQjBEQTRNZTJQUXgzR0dGaUhpeVlvU1IwS1F3RTFXNHYwNWtRZVAwZENLMDBL
        MzFlelJuUFF3T3h4bEpUV1FpNlRodzhVTUpnTDRGcGZIMGZpbjY4K3dLMjVlSGhP
        Wkx6UWF4YmIxZFYzWVpkajBZbi9ZSlRuZ0thcWJqdC8xMnJ5TGlNZWdqbUVVQTJF
        U3VzZTk2UzUybXdwa2Y5YU9Cak00dzkzS0RhTmpHSmZxY2F1L3A4OHZwNmRzcHpz
        WGh3R29vVGlaNkZBVEJlUkhrRGc2VGVRRjdNakV6QjBNa0xqUVUzdzJ4Tlp2bHZP
        MWpoZWRrcUJGQlNMam5WcStuOGpFNkY5ckIxbjhBSFdKWndsS1FJWU1SckRSdlZv
        ZFFRc0NseHF4bkpPMSs1RXF6bHF1ZSthT2RpakVHM1ZTVldxSzB2SFBXOUM2VXEy
        WWdLZjA2b3ZOL3o5VzVCUEhGT2xVak1seEZHZjg2T2V6MDhPREFPZmI0Sk5MVnJ3
        anY2QmlnVmNidm1QNFVsa29TU1BNanh0VE55WVNXWFZnOTZXL3VGbWIyVERIZk50
        VitkZU91N29BNjE4MVpLd2pRRU1XeThOUjBZT1pOVDF0TGhuRHZKbk1uSmt0aXky
        S1BuUmhnb21LL2JYOTgycExoaG9pNTR5YlBKdzlNWkxEM2ZqcU52ZGJpUjNMSjJK
        VGhZTGd3ZFhCZVZZMnhtWFdON3NHTmtYNnZTRnRKNUNGR2xEYmRTVXRPVmVCbW9S
        R2k5c20zdlBJLzBzRzVJVy8ydEp5VGY5SnRWL3lnQ1lPL1JzdllCWURwSVQxbjlx
        Mk8vSndTVzhBd1QySHl6Yk9NODZZM0NuSzhEeU1SV1FYdWJjU2NDYWJHaXBjZmpZ
        dE4xQ3orekxiV213bEF1TGhKczErcSt6TGN3bUJIalc0TGlnZkZVUmsrd0VCNGNL
        b2V0aVZoc3VkNGN3dnMwWUVkY04yMVpCNTNuQnVKSzBZSmVNU3dhMlpHcnN6cjYr
        L2VMeXhGaDIwd2hEdExjbWNGd2RNWmNHa3BLdjZENTdka3pjTlFLUFI4WWswckhN
        WU5wU1pabHFnRklxLzdPRHlham0rWVlKK29HNW9sR2RNaFRWcXJxUDVyTHBCQ3BC
        eUExQmxhZk9POGtiUTBmbFEwK3daQ2RqMnkyOURNdnlNRzYvckdseGlRY2pEdXNa
        WXpNWlRYSktiVTV2cUQ2VGlDYTZqUWJESXJaWHJJaEVmZkRvaldSQmM4Q1pJT2pU
        ZXhRVDBGZTNNT2pUcTRmcVVjQnJOVE4wZVZ6QXlYOUFPQ1pKZDZyOU11WDVtNFE1
        Q1Z3QlRKQkM1R251VGtqQWhndy8xU3gwWFdScnhKN2RlNlA1QWt0UGt4WThaVzZo
        bEJrb2crcjdJL0d6QjhIT3ppekI3eThiRm1SVk8rZE16Ukp3dW9Qc21MT0pkSk03
        M3lSRlpQOG9KSWR1c0FnYUl5MEUrMVhNbDUvb1A3bFIzcSt1WXRueUhucUFkUzNx
        YTV1Nk12MGxvcjdoSXQwcGI0K0FjN1p6NmJBbjhDemIzeTFqclRId3lBZUh2NUJm
        NFQvbUIwL1NjT2dqcExER0QxOHMxdlZocHdXVXp6ajZFYmIweU9memNodDF6Tmw0
        SFR1djFTZFNtNVFuT0c2OXhGM3JtSldyYW1pVHhwL0Jac3ozOUdEVHRSZktWZwpC
        UjF4TE1RNjdoWjROM0Y5NkRNZmd6enR1bS90Z2h1WVNqd1NwaE9SdXRJCi0tLSBH
        V1VFWGZzL0dMTkJNaGFlYStjSVhROWtqVG5nVXhPb2pYakg5Ky9HODNNCkKIWYdB
        gQh/TBbpBItmzoIQPF99/HkhgJqWbuMmGUmAdOkDg8WoqQzE7dvOWHhrmzkXawa2
        jVPi61ovqtmEK0g=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T00:03:05Z"
  mac: ENC[AES256_GCM,data:jmL8eWHhVZQ2XzbP7Q3xUQU/2vYtVZ+UKBMzKLiu30P9dJid05H1SOA55QqQNFAhPaKBL9TOx+/X1h5b2egOWT7D1Zp3j2p3E+DoAHYx/T99yE1J9B6r+iSPILA8rGZqS8N0TQByEQwiYvdGneNIJxDvX9wFHAapDeX/RB/m2/8=,iv:nfp0GeV8eG85DsgzwpNT5Gfykz1SbRuSaAqssLJGaho=,tag:a3Z8GdZARx5gad+6U7iWQg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
