apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:tGzRGMHcBYrQImc+sQTt8ydpZ0VQGWknfk+MJ9KjmBM=,iv:t7T/S5dXIrQ0J7T+ESOk70lyOnmxxqt4D+3dQqjfezM=,tag:Kb8sAY9ydmRBuwBc+8nlnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFZtVVRsY3k0
        Q2dENkNOdXlvOEMrakh3QjNpcWwxSmd1QlhLOUNMZTJhL0VUYktwTEVkOTM3N0hw
        YWQ4YWFJc24wUkc1SHMxWDc4WElSRXBjRHNOYVBHTi9YRW9WdmV2b01CQlY2ZFBs
        Ni8vUVdRY2llNTZ5UWZRN0VQeXJuVnY4OUZZM2ZaM2ZRa2RDZ2h6Z3Mva3FrSmNM
        NzNDYTBHa0xrc3VNaXpHQXdlVEFrd2JXQ3hmeEsxSzhlQ2Fva0V4Sm1vYjh2YzRx
        MXVPSDRCUUQ2TUxtOW5mclNzV3RpTGE1d2lrZjBYNkVJWGhMUktJSmE4SStPQnhL
        T2ZqTi9yeUJIUFBQVTRSVWxiV2NaMzlSQ0ovRCtKbDh3VlpEOGtJVzhnQjJKMXEr
        eEJHUEFYWUZlczhyTGlpTFJEWUlTSitzdWswL0FER2pWTFVVbnNCVm00Ulc0OWRC
        T2RuWForUTVZWDd6ZFhIOFZybTVpdkhWb0xnTlFCZFN0NUJ5L0xLbjZkL3RGNVBx
        S3MxWnp5R21vUittQVRoSm5aQ0VaNmc3QStMdWYrZ25NNTlMVkxxR0ZnaWlXdnNu
        ZFhSbFRzVFZ5Vnc5K2cvb3doSklGMkZQOFRqbFJ6UVRjUFFaeUtOd2NqdWhSeXkz
        YlB2d0VvUmkyckpaMDRBb05UbUtkRVBPTUw3dDFjdFAvL0NlTzRTalkzckd5bU1x
        WDJCVE5JdHBTWlFJVnJSakEvNllEVUNZYVExL0tUVHNVVUtCNHgzV0NlK1Mxa1hB
        dzdlcFQwWnJ3VFBEejB1ZmQxcFNLTGRlcTJMdzZMWVNIOHB2TlcwRUcwRGVxSEox
        RnQySE5oWEFOUTNuTDY5MzV5NnpIdzlkZmlNZk5vZzg2UUVsdHliemNqb2ZJWlpI
        YzlOeFRxUkVYcDMwOU5EQndxWEhWQWl3dHdDaCtJdkFzYW9La1JTSEZnTHB1Y0FK
        L1BOUkRqQnRNQkRCN09WNW9kcytBMFc0MjVXOVNLbzlNbDdhUlcwU3QzU2UvTmtT
        bGVpNGhaOUgvY3RId1lVa2Z3elhVR2l6NjcyTDhDazc3MWU4YU4rbTVNR2pmS3FS
        ejQrZjFvaVprQlBzdkxaVy84aTNZNWxtYldvN29LQ2NZL2NUaFEzZVVMcHAySVpQ
        YjVjcmlHZ2pJczk4RkY1d0dBdWtHYWJDczVhbGl2ZWMvUDZVZUNNMWx1QUpkNHRZ
        N1k2YVFvckFSRjY5UFJndnFoT0hCMGNBTGlNbkFaU0xiSjdkU0FMWlduRkxSZVlX
        Z3YvamhwYldNTmRNejVvR0dGeG5DdXdLaFo2S25RdkNiYzBMVXdzSFQrZE1saGJO
        M08vV3dkY3pISEJld1paRHpBVXJ0aEdDa2ZRdTRxSTNuOFNsTnVLTEVKMTJQL1BU
        anQ3N3ZJL0MwbEFMOGF6ck5GSWNITnRGM0JQT2ZUNytoK2Z5MGtwSnQzd0dKRStO
        cU11dWNOd0FPVW1xOWl3dmlOU0c2OEhSYnJMRUFDaWptVEI4a2VHR2FBcmdwRzM2
        TWNuSitGWWlIdnlINVdURWpKSkxiVmd1WTVhZ0o3aXg5NlVaZFZ4OUh5NDVsQ0JV
        SG5GUDJDdWxXUWFWa3FmUElveWFnWmpTaWJtY3BCUWtTQ0YyaTdDS2ZtMzk5YlNa
        Z1poZXZWUmprSDdCRkdmaVBmYzB6M1psK0FZVjgrcFdIbExOKzZuNlA3WHIxVmJL
        QVgxVTI2aXZ0SXdTd3ByMXFuUVdFbHNudEd3VzJjOG9NZStvR1hPTTJxYXVyRHZq
        T1YwSitSdm03cktBMjMrLytsQVdHTWVNQ01TcXNhWUtGTGU0QWNxN1FKSlh1U3ZF
        bVpYTmRiL00rVEdHeW1xNEl2T2FpbENkakJ6YTd3Q0kyMWloOVA1YTlBeUEwTitk
        NE1iT2tDd1hJbmZYNWpEeXZZSDVCQWR3QlQ5M3JkckNKS3FxOHBzVVVnUlFRdwpZ
        bU5SOGVQazUwWVo2d1o0aXplRlB0ZHhTcTV2Wmk1dGVGZzU2N3dEZzEwCi0tLSBi
        UVFhV1AxUlo4UGxVOEMwWUhXbEJ1VlU5Mzh0Y0I3K0FyVUxIRm45TU1FCjGblN7R
        8nAOosXIJtDhrPXDr737SjCvxpNCT38i2EVoX+4KvARLf7BIh1ormka/N77tIlaX
        Hk0e5FiCs0lfcq8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T00:12:07Z"
  mac: ENC[AES256_GCM,data:d14B9fzE/NidHE7PiTYfyjj58ZFa6ZZwtY/omdkJb6pCqvi+PCwtqPSYZBNrxce5xjEtn5ik5hgi9R8NtSvp79zzGW3rWU3ciywjyYC/vDuLwTOBoFw9jp/8CX4WPbb7ciNFyTBBgqxkQxUL0bGGwZAcuTkoltEyKTk8mh34Z/0=,iv:2AAdTFFFYjWTQbYCCSrKePaF4lNsLMiew5f1pmVAn4Y=,tag:KUghJWCveICKDENEb1/Hdw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
