apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:uUGB0jMip92aFbTElbC/yTSpXcC58WC3k+5zfcW+XGU=,iv:9z/Tfy4/zaG+k88wN1lvXAAdQc25qzaqmvQ155IZRVU=,tag:B2NrqPAi5NepM/SLvWcf2w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJ2RUxveTF2
        ejFuQWZoUEVYWHVDd0lWUHdNOC9BWS9ZT2dNRkFsL1diZEVqdStoWlJNTzNzbkJN
        cFlmdVZMclBHTWEzRE1ZNnhVdFRIMUlLTHYrM084Qmg4aGRZTFlrUTNCQlhES1Rj
        cmM5aXk4RU1KQnU2V0dQVXFaTm9ua2JvL1B5RGIrSWZnRmdsdEMraEQwSmhCRUV0
        aG9YdlhWbkFJeG54c28zMTlPZWU1cGRxbVJscU5tUTBPeDcxMENjYXhjWkxlYXBu
        NVdZTVQ1VEhXZG5JakRTd09jaUJERjUvTmFHdVJ3Y0twQTJDdGJUZFVrb3puQVJZ
        OXJnWW9jaU9rMFZraWJxNHdxM1I4RUFrL2JlQy84NlhHb3ZQSFVTMGZMcVBLTDNv
        UGFYM0prUmV6bnBpbTBqeWZZUVZqWmVvRU40bXRtSWxvSUxpTm9OeHVhSk1RUWgv
        YU1wYU9aaG9KOEhSWjExM29wUVFLKzJNbWREU3NyMnNrTVQ4YTc4TTdDb3cvcTkw
        Tm9YY2tSMnhMSzlwNWhYaC8wTTNzWkNmK1d4T1BxQVBEa0xJZk9zVnpUNkdiRUlE
        MnlKVEoxRGNIbG4yQmlWUGp2Si84K2hkYlovRWJTOFBtdVBoRUhEY0xoNjB5cWVR
        S3F6VkhVUllRemdYV1YyZUZISk1COUVIbjJlUHVWQUZ3QWd3NDArKzUxNXE2ajhK
        bkVPTmpWcUhTMVBXblNuMHplUE56ZDV4RVpBWHlBR0hBcjBZYWh0U081Y3ZCNXdK
        T2RUeGZyOS9XRWVINzhnWE1JSW84eURIRGIyUEROeWdoSUVhdlFIaTZCaGlGTkpS
        eURJUDNQZzIvcUkvc3dtZTMxYkE5cUtoOHYyMkxKeUoyVmRzakV3a2hnbkJWbk5q
        N0RKUlVNc3h4OUovZzNGbjlRZWsyYlFsdEFpLzZvVGt2KzBRWFRYdlhzaVZhaHVL
        L0ZxNWFtZVZZbHhSaHdrUDJEdlVCRWRZem9PdHcyYytjSXFNTm5Hc29tRUdYZTVL
        bjNKSWN5a2V5Rm14OGRsSnQxN1dFMHlvTWsrdmlHWUNBOGlZQ0FqaWZxeUNDellu
        NWh6dk9oZHpFWmhHWmliYi9MSThRNTBRUVJQNzA5Y2FmaUdKakRoRXVBZGpZWmhk
        c09pZ0prRHJuZkdLQWRrZ0htOVJudmQvZnAySFE1UjU2VUxJOVZSUUlwTVZJQWFQ
        cTljQVhpT2U1Y2gxTzkvWlcveHJHMUw4K2N0eEhLQ1NWbUgxOVliYkNOSUxqT0VC
        R2dVWW1vY1o1SDUxTHVMMXNveXNicWorNWxXUThhOXMvZkxKMUhXQVdWOG1vNU02
        R1FKcGV1SUdFcFdSQ3JWZm42UnRrOEcwYUIySjlPUXQ3Wit2Q2lVdVR1V3J6RHdP
        M3pHdk50ajRQQ2FNeWgwRFF1Q29DL20vOHY0R2o2OUpVRFJ5NHA2OE02aGJ0elR3
        MTdJTXdDY0NOSVh2ZHE1aE9Rb2o0MnkvQWh2cjVHV2NjcjNUdjZXZWM4bDBTZm44
        ekhYMGM1aExCRW96NzJ3VlVqTEFOZFNmQ2Z4Qk9Sa1ZHQzJkUStYT1dOWFhjRHh5
        UGJ5amFYVEFFUzRvOU9ydTk2akxzWGxTZjdFM3BQai9tRGt3b3VDTFlNSmFMcnNP
        NWZTYlNMcko5aXFjNGVDU3VlbWJmdkxmY2NBUExhbVhWSktMV0RvM0IwUCs1ZVM4
        TGxTeEl5RWNPYnN0SlVOa2FDd3o0WHZQM1A0Zms0d1kvMXhRREpPYkUwRmhuOGtF
        SlRXWkF4MVFqdmNtWEJ3bTBpRGlzNU5qQzBZMzQ1eVBiTzZCRDFBT0JDblk3K2Qw
        Tm1xcmhIR0E4QmswYlpJNnBidUxMWk0wSmxSNklNMC9jbGtQT3U1K1dpNCtCT1p4
        RE9pd0pyN1ZKenoxRHB3Y1VWNTh6c2NzeHpFNXRrNkEzeHZpRkxaS05sMnlPUQpu
        UjdZN2dZRVVCRFdFOC9pQ3VOQm5JaW81clRTYjFoVFFhY2hBREFhbjEwCi0tLSAy
        V2VNL2ZFbUQyVStlaytVdUp6Yk1KN2lsNk9rRFlwSVBEVGxnR1o4L1JjCpcr+/Fk
        2C8e99LUhj3Z/6nq3itEqz0y22C8GwjKrFdFQVfkQPC9Ep02yqc3knQUtZjzpdQr
        bQH94unFajJlRUM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T04:10:21Z"
  mac: ENC[AES256_GCM,data:kbB71NaJfKLM+YqrkDQ9OSKjm+Ap6qn2vJOe5A1IZ/DTT6aWud2j1dB5DWmXhG3AMUIrvZpHcdBIy+LYCWHT0uDKvGrQE96qIijENCCF+6zbZXD0j/H9k6RwZGcEuc2/9P3yR4AL9+ATtQdFljeXV6aEPalf1urjQyhhC+u8MSI=,iv:3227WG2OaPG7obuj23sjp3V51iURsWNFkXpX444EDHU=,tag:B6DK0ADxooBMoCdnuugmqA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
