# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kaniop.rs/kanidm_v1beta1.json
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: kanidm
spec:
  domain: idm.${SECRET_DOMAIN}
  image: docker.io/kanidm/server:1.11.1@sha256:7c3d7ed868e91f78c24a7fb9c548876563b375a4203021b730d58369b97ad154
  logLevel: info
  replicaGroups:
    - name: default
      primaryNode: true
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 512Mi
      statefulSetAnnotations:
        reloader.stakater.com/auto: "true"
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: kanidm
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: ceph-block
  tlsSecretName: idm-${SECRET_DOMAIN/./-}-tls
  gateway:
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: envoy-external
        namespace: network
        sectionName: https
    hostnames:
      - idm.${SECRET_DOMAIN}
    backendTlsPolicy:
      validation:
        hostname: idm.${SECRET_DOMAIN}
        wellKnownCaCertificates: System
  groupNamespaceSelector: {}
  oauth2ClientNamespaceSelector: {}
  personNamespaceSelector: {}
  serviceAccountNamespaceSelector: {}
