# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-admin
    template:
      data:
        password: "{{ .ADMIN_PASS }}"
        pg_pass: "{{ .PG_PASS }}"
  dataFrom:
    - extract:
        key: forgejo
