apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pbHz57oB1EPWXZInW+uYzEfsfWafDYqB5HMesUQiUJTIE5KustneFUBN2DtIYXEEpp5qhPGq3B7OdobtmS1h382I12C4JxG7JdvXZac2Gw6NdUj/Nfe0RCaDDvHtipp7f8u6BClN32aZsYvU0Zm+HB+UhO8+YdxhDWYe6+vnAGrvpn4LNMa/aJDQ8qitkwNm9P+qflIAqprDu1eUuXe7ti7rsQjUAlVrESOyapmbD6sLqTQr,iv:PUroy6wvBx4Si/iq4sgNNeyOiui7SKYSIe1zruSBLP4=,tag:0mR3W6bwB1Nt5dyJAsrzSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDhCMVNPZXhC
        aUphNDIvRGNYYkN5UlRGcTR1K3pxYTNuRWJnb2FVWWNVdWlSRllDMnRLM0VQanZm
        bmdnSVMvMUdPZUozYXBOblFpODNrNnNXZThadUFuS0pUWnNscWNxNmxJbGNSWmhv
        RitVMmtoWmo4aGUwRlIxN3g1dVdZeURLamNkaUxFN0xBNGZSNUtBdmg0V1RuNENo
        aFBNb0NDYzh6UmFEbWgzbUQ4Y3cxQjIyRll4bmlWRCtlOFB1Y3BSTy9UWDgzRjFV
        MUtLU1lNOW1UbDE2YzZXSUFZUmxCUWJWbjNsaE9wQjdzcnVEbHpGYy8reUFDZWVy
        ZjBzbTZrcGtJRGpORXVORTVyZkNkeUt0Wk1sdWdrY2lBV0tJOUtaenZzS2d2YWYw
        c0lGMWZDTDFGWi9JQ3VGNDVhV28wZWJHTWFDQmN3OU9heEtVVEZQTllrVzI4SHBo
        eWs2L09KM1QwaW5UWWdSemI4S1UxaXUwVkJIU1kyU1hPYW05ak1jOFdwcHNmbnZj
        V2g5VFRTSjluQWJoYzl1Z3FlQjlncGxpSlFiT1JwQUpyZ0VHbTdyMXF0bHFhbEdE
        ZWlta255TkNjTGNnOGRGbDlydUtXaGs5VzVubjR0dmUvWU8xSHRWbzdmSm5UVHFX
        U2oyY0ZHYmJCQStXcmRqWlFzSXRwSVNqZTVTSDBlL0hrZlZMUFpCeVBZUEVFTkZu
        Slkzanc3YWZ3c2FhNWtLNjRaQTFFcWRwRE0rcWV4RitjSDNaU0RncmNHT2t5ZTZE
        ME1IbGxlZ1ppSFBSbHFRbzljTG9uY1J5RG5YM1JmcURKUU9Td0U5NjdaSGRtQk9Z
        cUdIOUJ3RUg3dWhsSXRmanI2NnNWQTdkT0RxYk5vS2w2ZG1qc016VW5EaUxqSnRF
        YndEZSs3V1BRa3JKcUZObkQxK09BMUdQK1g4WTdONTBGS2N4MjRvUjUyMzVaUFdm
        K1p4S1VyR0VTS2hxbUZqQ0NuVlZ5eXpiQjlUN0NQWmFqU2MyTGlXYVQ4b1hXM1l3
        S2FpcllZUXVYeFZjODUzVW9hMDdFbXVObHk4aWxNZytIb3FydEg1Mmt0T25IMnBk
        VWlsSW5mREpxNWZibXRuRTArajAvM0IzZnJja29VRWZPdldjTktEM3I1cW02TG9U
        d1F5REg0SUtKaDNxQ0tNMEtlODU0azhuN0g5T2M1b1liajRBbXpXdnp0aWdYUDBP
        OHFHeXp5SVRPTGtZMWdOMzk0clV0bFFpV0VraERxOXpBT1BhZzNYdXR1R0VURzdS
        bWQ1MmJ0aWpnSVdtQ3dpZ3RxcVRKOEZ5K2Eza1ZubGJTM01Eek1oOW9IWE4rMExk
        UkxOQWZXbXR2K3RYSTBMdkhTZ1N0dUVuQmRPb3hxQ0NBWERoSVF2SmtXT3RkMUFX
        S1gyaGhlNlhNOHJ2dzB2TW9rT1pqOXd4WDczS1ZNNUg5dWVPWVZhd2xzbXd5dEgr
        NlZsUHBTYnY1ZTgvKzJ1YlVDTUFZSzc1c3kwZHRIYXpkMVhNVnNiaFZRQnUzMnBm
        bmNMakhvbDNSVFB0UFYvRTNGd0hTZHFSVmxhcU1RZzlQbnV0SDY5bUhHemFCZitV
        Zlh1Q0hSKzF3VCs5QXdVMFZneHA1QkY4d1ZxTVNvRHJQWUE3NGhEV3YyOHNlUE9I
        ZDRUbFNrZlVnbmIvdmdMcnlmdVhFODFKWEVWdFNYcFBsKzdwNStXdWVIYTBCb3N5
        RnpIZSt3NEdBdk1zVGt3b2dYWDc1ekw4MFlHUVV4VlhKdFdNM2NNTDN4TWcybEdX
        Q3NyQi81TFhBY2RYamI1Q2toNGMwdW5zbjZESkJMUEQyVW1LOWQwMHdSckd5am9q
        VTVpTzQ4eWgxYmhFQUNTVklHSWZKV2diR0N5WDFoUHRrYnVsWHl2Y0VuTmd2UzhR
        bk4wcU9IZ3BYdllCeUMzcGR3TnBacVlFbSthMGlQTVdNM0R3L1dJc0w1bE5GQQpJ
        cUlzVnRDbEQ1YUNWaG1KeGdNN0tzVFpRenZ1TUh2MExZZlpiWGpDc2xjCi0tLSA2
        T3JsMFBFdUYzeGtJYjFZcVVhVUY4ZVlpaHp3TE9rS0xsRmtMWjVmNGNVCv6Tjb/0
        3F8FFqfdggFOQx0sDjciEB3hxrhrgviYkttbMYgaw6QU1FwxfrYdP3obaWUtCLK4
        /FDGxZ8xEUonF6c=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T02:34:48Z"
  mac: ENC[AES256_GCM,data:NjReB+17Z969xkxUN8WBz6vew/HNxA5DAi7bI07XwrJroRWdrnzi+Wfb6Qn01g1o7jdY59HUxll5yBDKDU9Kr+sxpIDoNzxrGJNVLhA2MC293VKF6jmtPc/p+0ykrRvjHLHftCbK/mOspDU5CECVtYYWudax4Wu9boxB6mrV6YA=,iv:Z/ESxozTTaW4Ed0XAAUKfcmNhFOdDFMLzWudWOTQ/xc=,tag:wFj9f2aG8v7MmVnTWfFSOw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
