apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Km0QOFEvDASFg8j6MajOMZDKnLFL1tcI8Ro8dtNqOmpoBwAmBqcp91zB6l74NqobtO+XpNe1RvUAGBqCMA45cU/gxjdz269xuOlB6kfaLbrWlDeh1502PuoxX4KSIHeykH/DDoKOFOamfpWkIYwvGjjCMnA2dI621hhPSWdLrHXV/SS8cl1826kdwAZnqRFfkC/o3YXawuEgDnHtsJ33IUR7jpMDyTdBM/adsxFPq8JEIf0E,iv:111FKoHLWI7ILGoo3sTN3zyoBJCg35+Lpm9OV8+EfRM=,tag:iT7CL1MXU1LqDpFH8ykgeg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGRJcUVZaWdU
        VEtqWFRKUnhEUFlMZTlOVnFpZlVYb2lLU2lKK082dkFQMzBpU2lhVldzMFVqcGha
        dTJqMVRnd3A2NjNwWGxkdTF3SHNSdWJqQVYzTjNLUjBtNk8zVEMrT3F3T0QyNHht
        VExia3RvcjdLcmw1VDhjZzl3VC9ESHlQUHExMXpZK1dsQjVHeFNRTm41S0dZcExv
        R2JsaGQ1WTJ6SFZTVzlzS0xCb3BmMm50cWNSR2tYTTJTUWwzOXFkS0tCN21CN1Vt
        aHdOOHFMMkZWa1E3NWtBbGNVdEVvRUFPZHByTjlnMnpHYnFJN002NVRlT3AwWjdZ
        UFRBNmo2WDdiemFyVFgxcHN3V2lENUR6Yy96VUNrdnFucjlyaVBzUloyKy85cE5x
        eEcwVG4xekxIbUR6QXBuUVVxZVNLYlBmYVVoRlBJem9IUHlwSG0reTF0NkFDZ1BB
        QzNDRzFaTkpMbEw0V2Y1bUpPVjlBcFo5ZEJyQ0o2N1hCejFwRklWQWt1S0Zud2li
        TVdWYzhnaGJCaENmYlFqNVJycEkyaUNSMDJsREpyTXZlWndyTStmN3IydWNLaGdJ
        RXI4WHRLQU9UZXJnVllhRGkwTjg0Wkc0Qko3QkdUamVRdUp1bU8weVVQVVBiVUla
        ekkzdHcvckR5VlNQczhlWkZVQ3BEZEVWZVVjSERUaVc3Z0VYZ1lJQ3NubVRhb0ll
        UGRCUEdJaFRGSWZFZ0gvUkdWandGSm9DVUpvNWJuVFZRbjByVU01ZmtVN2dVSS9p
        akdFQ2tSTTFNYnhFY0tQMzdKaGI0KzBsWlYvMk5hZi9JZkZZTE9iOVU5dGFiRjlM
        ZmM1UDN2amZzWXA5LzZMbXhhdDVsQXdxVDRIditCeThCYU4vVU9zRW9VckJQbElp
        eWZOVlRnK0I1QWx3RCtsckEweThJZ0U2RkZnN3pKZXBIS0o2TWRlcnBGWTQ2NGVh
        MnpLelQ0UEV1WmdUNHFIMUdvT2NUSk1pMWIxS2RUODhmZTdTaW5PMkM1NktyWHdV
        dUsxM0lwMTk2VkxLQ2I5d3lLRWdsOEtsZXJtVWltOVh4cSs2dThmTEhPdG5KU2hh
        cUZndnJzd2tjR0VScDZ1WG8vLzB2QUZmK1VPcGVEYmpUOTRaT3VqS1ZWOEZtc0VW
        Y3JleVVtNUhvS2tmb0JMTE5Oa1p2bm9USGs1Yk9oQjc3Y3ByYXBVY2ZDK2FTdzJB
        Q2c0ZHhJeU5UNHRrTHZlT1lUbUdwbFBGUmozR3RmS0FjRGhVamNEV0tCRDJyOXh6
        QVBPMm5UUHRyNFhPeXVJRXBlNEU0K29jbTU5N0xtTFh0dXVzNGREUTFjRm9VR1NB
        Vmt2ZnZyM1VxVGJsR204Wm9xOUN0NnVMZTJkQUxBUFNUODVvNnJ2UFMwc2d5T2NG
        QzJnckgvWkt4TTc5bUxrWm93WkZOM2pUU3FDdHI1UzF6WGcyOTBYdWI4bFhoM1lU
        V2NWM1Z1NnRSemloWEdWK21GVjdtUlo2VjBwVnpGTTZCN0Nkc0dGNW1pVFVlb0s4
        dUpyMkY0dmFxU08zUzJFTkE0TmJwUU5pUHpWVFdVOENOSTRqa0xSNE94TXVjL2RS
        enVDWlVyUXJqbkIzTUgwaCtSOFhLWW1Uak5IRTBSSzNpd3JZSU55U0tFd0Jkakg4
        VVE4LzNZQVJva25OVkJ2L3BpVlpwY0NwTEp2V2dKS0tsbXdVS2U1aEpYem9JL244
        WGI1bUdqWGRKazkzN05JdnVDWVpRbjR2RU9Ba3JNVFpUYklMVHR5eFNuek9ScWcz
        K0tTaDZ4K0d6RFJCUVRmb0xacnE0UWR2c2JSeXJubHJua01peUVJdWwyZWdIZFBH
        eEZIK1RHcnFKUng2cDdUTFc4TEVDdjgxYkZWc2VsRUsrWDVCU0lqeGpKTFdnUEti
        UDdPWGF2TTlYejJldFZBSkdHNGxtTTFENUFQTXN4NXdySG5TQkxjZjB1QmVJUQpC
        UVNGREZUeHNESTYxaXpnS2xaL2labXpHYzBHN3FOMUV4U01jQnBobXFvCi0tLSBp
        SjBwUW1xWGZWSWgrRHFYNHNuRXJ2S1Y1KzhSazQzOUdrb0t3ZHlOaDRRCrwv0cSu
        WHSokJQSHeEIAtHc3gyBRsgQZDoWAYxlMjd1No3xSbEx1ZuMUzSAj0I6zI1yR0JE
        CAcm5P2DVXFl1iM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T00:49:57Z"
  mac: ENC[AES256_GCM,data:Iobi/74/jRxnQfmTFd/kJ3qxDsfIFXKsDmDvKvfbjRvix0RoTRHSve0qd/Y2hc+vDexPnqH16BNUmQWLk379KJSUJuO9xTt/oRWl0PLejeL+OcCimmynhzu74w24jbu+gX+//5Edvrkq4SjfX1fmnoHwXm7J/RXflVnjWX3jIe4=,iv:2MIDfOJqLQe1+JfqUkq9Er6rUodUojOACgTo64yDmm8=,tag:3aUQgtC10URpcq5sdUlQtg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
