apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:HgEMH9CyV+en8s9hBbb3A5ncqHUbqJEFq0zz5lxOxJNwcz6ILAqW1o+joK/yGlU5sT+fUkEl1KYsF7VXGKKF5jSlO/NBbu4+MyGp4SrlgQGIrJSjRfaa+4QzD8Ol+S/W79VKJxREamazHlUeXfWxomW5oQU9/9gHnYssQv+4fFfpXiArHO37JQitBBXkxoRda791LALQKqsIRWvAfQAQbLKPLH/+ZFP7Gbk9s7wn59P0Cw/t,iv:wtcrNaDHMYVKehapeundYUsAisvlKwLeOTln5tqV64c=,tag:c6cqxPSGYPj9yVEWRW3LIg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9TYWJJNUox
        YTFZTTFHMU5STm1JYmFZN0xjOEgyampobHdnTFZZaEwxbEgxYjR6VHY0NklhaVNX
        dGZKaWQwUHJ6VitZZFF3MHdOck45UVZiTERaekQ1cE90bVNYdVJCV2JkWVdTc2l4
        Nmg1b2R0YnNFdUtLV2ExckRQV3RZcnN5OUZzbjU1YzVYNG54dllBUU5Qc1hxYlVV
        b1RHUmZEV005NGJNZUVuZ05YZHU4Z0xFdEhTREJDSTNudFdJYy9JMGw3eE5uQXp3
        dUwyOWhIT3NXOXBXUUJQc0NaaUNmOTlLbTJnb2ZnVHI1U205VGFidkRGYWhHN09p
        Wk5pbC9yUmZpdWZJOGdkM2hmYVV2djJxVTFydksrY0FEUjk0dUZFSGZnWWNNWTZh
        emFFYnB5b3NtSlV6Zk13aWw4ZnorQ0dlNWZCZHZzMlhVcGhkaDZndnlyUHhNZzhv
        bVRKQXp0WWZxNDg4SVVkNXQ4Rnp6T0pqUTFvZUlsUWRib3graDJQd1g2OUlMeDBQ
        NHdvbEgwSTFtYlIycjlLUVgycnIwQjFMamwwYVhOb1g3eG1jczJEU3dELzFuZVZ0
        T2x4Tjc0dDQ4bm1KbmFkbHJPSkNjQW5kejdKS3NzZVdJUHViRFdJakJiVmk0UVNk
        OXhESE4wY2hyUk0xbTAwaHBjMUk0SHV3QjEwM0E3dXR0RVY3THAzcThpMkR1SUFO
        bjcvVWRQaEF0T2M1YVJndjg1ZXpPMHhKNEEyU1ZLVjJBZWpwc1hNOTZ4UnVON2h2
        VjB2MnczNnJKQzg4R1NDUThqZm9GSmE3TUhEb3M2ZUtPdUg5bWhqN0ExcTZldVI5
        TDVyU3RCaFdxZlJsUE1ON3MzbUwrMHlvK001TjUyWko3SXcyT1p6enh1enJBejV6
        aDBUUlhrVW5SelYxUmJaV29hVlJ4amhJc1ptQ0o1UG1rWHovT0pieTFlRzhma0cx
        dmJZT0t3dkVScVlEYVQ4d2k3WFhudUNUZDhFQnFNV2VYa3M4TEhLWVRjMHIvWm54
        RGNZalA4cVlCS3lFcnVvT21jUGFMaVp4bzY3ZHlBdkp6RkFNQXpBR1hXOGVVNDEx
        TmJUS2RJUFJGcVU2QnpKUE0wL0FKcjFyaVAzQkh1YVdneWtBZW0zb1k3ZlZYWnk0
        NzNnVHpmOUhWMlBWU2NobGlqQXhjbTNCU29nbkNmbWZ4ME5jcm1CMTRnZ2J4T21n
        VVdlOFR0cHhFMmJTMmE0YUVXRkgvbnJnMzIyQ0xjWC83MCtIWnVVaElZcS9MK2dE
        ZTBFaG9VMG5IR3B3dHNtay9CK3gzTXRvZm54bmhIYXc3WHBEaG1MOExjWitxRzUw
        dFVKdUtXb0UxTXhsZHR4SEdHbWVHREsyVHVzSklyNC9Zd3BFWHpoVHZxMjluSkl1
        VnVLL3BWVkxCK0JTWjRJY1VseTZycjB6elBNdmE2RWRwNERXNVA1b29ERzNtVW9m
        RERtbnpTNVJNWklOSGtIY2xaTGh2RlNTZVNXRVdFSHRDRFhlR1RZb1JveEV0cU9y
        ZTNLY3pTVUpvRkdyc2dRRnBWZExlWHBhb1AvU2EwU3YwSHh5SjhFRG9xaDhCY2th
        dExEMGVkb2tSbUlZaTdTSVdsVmcydFFSZXZPYWtvcW1aQm8za3dFKy9ObXY1dDM5
        dU5VRm80YU95RVJiYzF1MFdXdlpnZDY1aytpZkpDZFpLT3VnRzZxQ0dPbWJteFVk
        blNKMnpMTFRHZUpUODgrcWpWdk4xTDV3ZkV1WFYvdnFzRUg5S1lhL25hTEFMcSt1
        WFFiOEJ0V3pqNC9UMGw0OGJqdS9NYkRtR0ovT1RhYi9nSUZBVE5Pd0F2cEp3aHFP
        dlBaeFE3VHlNdzZSZi9nNmhIdEVTaGhST1RNL3FmbUt0M3cweDE0Y3lkanBYSVls
        M3VyS3MyY1ZxQUdoMlNDcEJhWHowTDA1cncrWjgvQ0RxTkVXOFdqSVZ2SE9SdwpQ
        YkE4VFhnT2NUMzJSTFBLQ0x6ckhwcy83TTJwK0EvcW8xcW9aS1BwNzNzCi0tLSBx
        L1hZMWpmVjRiQ2ZpUjFnZjJaekNxR3NGTFhMWkpJMWZmQmd5THZFZlhJCtPhbub6
        /r4Ov2dHPg4ZGFeWo7AmdPVZ9y/MIIl2ysK29+185g4tSWBzUEHQXuLeyByau6f4
        WT4tXr8VPYDFQVI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T04:10:21Z"
  mac: ENC[AES256_GCM,data:GSFZuAEFfZvmoomw/ClsjvHIlRj3KTxVr4qmzeew4GqQTcWyNiu/GlQ2d8s0t+GZbr/NVMWZex+r+YwAHnHWWdr1puOwnFqHBHJ+uP/cQMIfRksIWtCu4Fty/Sw+yrutpDo0MbFp/8U0fi6MF7RzMDLHA2YfJX8PrbrtTOowT/8=,iv:S6u9dF5dXOm8Hl/1Mxi2Aoyds0v0AdKyXLoxhhLauuw=,tag:2b9MCyw43bHprHuio4A3Gg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
