apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: &app headlamp
spec:
  allowInsecureClientDisablePkce: true
  displayname: *app
  image:
    url: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/headlamp.svg
  kanidmRef:
    name: kanidm
    namespace: security
  origin: https://headlamp.${SECRET_DOMAIN}
  redirectUrl:
    - https://headlamp.${SECRET_DOMAIN}/oidc-callback
    - http://localhost:8000
    - http://localhost:18000
  scopeMap:
    - group: k8s-admin
      scopes:
        - openid
        - profile
        - email
        - groups
        - offline_access
  secretKeyAliases:
    clientId:
      - headlamp
    clientSecret:
      - HEADLAMP_SECRET_KEY
