apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fOzSvC4HndXD5iHYsfeIMi4emxap/ZQ/DyEc93w33ncTNAiSf0IYuparxzCtfM+QkY9Zh/I=,iv:+jXBcjTdLohnLoCfprW/9/Sxf4SwUpHF+KHmh9c32oo=,tag:T2Y/GnVDHiBj7Udw5YHmyA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGxCbUg1Zzk1
        N2ZwMmZKWjNHTTFNTnVvSVFJaW1SSVBhZmI2bkpaR3pyTG94OWROT1N6R1hXYTFk
        ZVZjeXJrK1kzamhRcEIyTmlNOE54THUzTG0xRW4xNG5JbGxNMHdvMWtMUWpXN1pJ
        Rmp1MWlrWmMrVVpWL3FVQTAvakxHczlEOFdjbTNlb1lHQmZsWjgyelM4V2Y3ZXg3
        V3ovQ2xLalF3MUpOT081V0FMT2V2cjBSNUxzeUg1OW9rL2MralFyaThtK1RlemZo
        NUE0eDh5SFp0RHpxcTBnblo1MDBpSGY0bXYxSDNVMG9qOFFWM1BxR0xxNUxydGhq
        L29KWnYzdXBtTGs2N2c0Nm51MGVCWXRFZ2g0RzRWN0FiR05VQzQ3T1dIdVJsYUEr
        Mlh4aXIyV3o4WlEvWnhiTkZkOUxPT1EzRFVYU1RZUTJYMmlIdnM3MEZOSUd0RkFH
        ZFZaNGp0TjZsQkdGcFhBcFl2aGhGblFoU2NSam9OaExUb1lyc0I2VGtpZEsrb25U
        VUxFY3RmTGZvL2R5TmNKc2JlOUl5L2daM0d0dll2SEVnQmYxdzEzOXlJbUhNMXBj
        RXAyd3V0SGFvWWxXZHdjc0N3NHJGNU1HbngyRUphS0xlc0NnZkNDbFNaa0NobmJk
        THZJU2dZY0hCVmJmOExLU3VRTGc0UlNXa3VadThpOFdKMDhycm11L0ZzRm1ZRjZL
        c3d6ZzBETUJVOHM5RHNjK1ZSSEM3RUtvQ0dqTERBdENWRTRkV20xa0EzTnN1Q1hC
        UVZ1Ni9DNUEwc2ZHMjF0UU94UnVsbVZ3YkhXRmpkYkdGUXZ4OWtEa2NsRXd2ZVFz
        ZStWRFpFWVVLVHNvazFvVGo4SmtoVHdlUXAweHd1bHlrT292NENoWk4wUWt5Wjhr
        UnFqOVhDSzRoMHVYNEZqODlGU2N3dkFJYmZNOStlRWM0YTdaQlJyd3JSK0NZUjE2
        REVDVlI0eUwyandpUVdkYUF4U1cxYWgxMjJtckNoQ09yOU1RaitzRWJ5MWR2YzM3
        bFVwWTdvZ0FzOVNtNlJvai90Y0Z3UGEwLzhvYXBjU1NyRmg2V3JxelhJWFN3S1Ux
        bmtlQ1k0ZGpTR3ExZ2dFUWJXK3MwNkdEQWFqR1NPVkRhTy9hUGpBamowNFN1MGti
        NnF3WmtHaTREQ0Z4a0taOFhkY2ZtNEJRK2VVY3dHNlNTaFRqQmhoRGJveGN0ODlU
        bGFCdVRlNmNRVDRtNU5pQ3MvU2dTQlduRW0zUHNqVHV0bkFlcy9Jakk3SUZ3cC9m
        TDZtdHlRamwzWW1ZbFBFS2VkNGU0c2hvYTVybGt0bjVnZ3diZ0JiQldPUTdraFVW
        SDhSWUpoSndJMkx0cjBKUUZmd3VSWFRXelBKd05MVklKVk13ZWplRTNpd0tjOGhZ
        MEF2a21xaytITWFucWc4Q3NqKzNxeG5LbzBzQ0xleUx2eStibGxidTJQZG9Bakls
        U2hxOWxIckNUWXVqdWxWYlBQd2dqdExtSkllOWhYSlZUVzJZZDUwY2lGNnNoeWxo
        WnlQelVISk13dVlNK1g4QTkycE54K2NhVSs3VFY1RUJaNmJPZnpEVFc2eFVZTUdZ
        ZjdPQ1ZqZFRsOXVoMnRCVnoxYS9oV2hZNkQ3N25ubE05N241SW9VK1c5RURiV3Ro
        MUpFMkNHQU94K1FlVitqcnlsSDN0WHBRdlBYcDJLQTNkamoxbzNmSW5MNW5lbE1R
        MnpKdWo2K2tmVlJwalRON1V5RnltZDAzUkMwOHEyLzJZQ3ZTMStpUnZXM0ZSYUFN
        ZElrdkpaRlNPZlhycUFUd0xWUHU1aHV0WEtEeDZKaWhFSHlFV3prU3lSdnhYNWV5
        Q0M1Ym91cUVES3ZCWXREN0NIWVFWRDg2VGYvd3FTMkE1S05OUWwybXN1TExOVDBO
        TGpHZEJjamhoTHJqVUttVTRBdW5iMCtaSWZMRmlZTlBWYUl6RTNLWWkwdGNGdwp4
        S3N4QVZzc3hieDdLWGtuQ2ZuTmdGUGxZVk9pZkF4RnpudlE0ZVJzSGlrCi0tLSAv
        dExETzRhSzU0VWVqaEE0ZUpRaUZqOTJrc08xd0VtNEVHVE56WC9EaHg0Cl+D+MRe
        OqHJGcP0KWzF57vnZr513Oza/iEVDFu4mQ+erqTVMX/7waBcQH1LOy4at/++d8YC
        Rk+AfDn/lXv2Sug=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T00:12:07Z"
  mac: ENC[AES256_GCM,data:ds0l+AhPaW96g+CqR7Ok14kO6KgQcRHo1juq+04CXjfo9ZKs3ke3CfFXCEaJVOfQ0kjI2nU8+UubOLrwYiQDPHnM9ot2rN1V6nxQ8L5m1l1EfWgkMAML/K+A9mr5WILDVZjw6IXhuuMvPfnLyYuB7jZm2o5yjPAe5UDFB6XVUxs=,iv:vSWVcYOZidJflzA4jSOqKPLW18NQR9jyO+HmEiXdmOU=,tag:FgPQHPdZx2vsr6CoJuc2Pg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
