apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:lAauzu0KDVknVWSiNiyvzNWWwypUB1G4a69TGzWX6qSU9jl2Icihy0OKInDD4x9PBARmsQU=,iv:tOGhg9xm4JM9iGU4A06d4DOELT8wNcnCYk+Q2QXlwVo=,tag:2GCl/SCsi9EikpMqDaZ1oQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEJOcGpnN1Zh
        bnl1NzJmdERtTjczeC9JSDczVktKVWpXNzZKdW4xdXgvaHY4elAreWlEdFpGVytk
        UlhsdTdBWFBKMXpRQlVPYlhXdXFKbnJDQ2NqQWljdjlPMTlaNDM1OEJXdmFLeHdE
        R2V6SGR5Ui9WTHA1RGlYeDFkQ3NRZUVScW1TRUlXcldHaUp0MHBwM05tbU9BZDFI
        a3kwMWNmaGxTZGtFS3lod0UxazdwcVR5YWRZZ3RhNzZoYlJ5MWxEa1Z6UWlsMHZu
        bnFDNFdXSDQ1dFlqTDlJUE5vbUdLMHEzM0d4T2gvbDRNK25XTzI3TmRPSmNYZzFH
        b3FLc2ZNSzBtVERpWTlMbGM3Z1c3WElPbktvTSt4cmwybVZKTnBFSGU1TFU1QkhG
        OUZTSTVYc05QQzM0djl2Y1U1RzZmalp4ZWM2c1M1aS9CbzJkTmR4RTZEbkdWaG52
        NCt2clA5WDFJT3Fuc2pGNWVRaE9aRFRHY21PeUdZQzRMM3BTcnhZcllIWVJ5OHNh
        YkpKRVQ4bjhvSUdYMmlYWHVhV0hwWmlTUXNKUkxlbzJIT3dwc0VpSjEyTzROQkxF
        K09jMXhoTFdJT3ZrQXNORUZkQmgwY2k0UjdvV3F4MC9NRFRHZVo4alRjWnkxaFBt
        ODVTYVQ5OUs3b2NvL3NpaXB1NmxsTlJHRU5pNVozWmdBSmN2MUVOTHhUdlMyTHZF
        a01oU1N6VmVVQ3ZDWlA3Rkx2U2s5U01RRW9WdHJ1RDdudmlFQWpjSDhTU01tNWxa
        N2RYT2dqN3lwUDI0QkxWUzlSVVlPWUdDOGpkdlpzNmhYaVZ5aGgwODhkazRtbXo5
        czJ1WUZia1htQWNTNVVOd1VXYnMwV21ST0hGcEZjak50cURhTllDL2RTcXhtbTZ2
        SFZ5aFFaOHpvclQrdmxYOSt6Q3owSVVPZTRpemQ3TUZsUUlrQVdKQ2pzODQ4OEdp
        ajBnSmdlNG52ZGVRbVo1Z0dLeU5idDJvUlZ4dzNYaHBxejBoVEpPcTNpZXRkSDZ0
        a3dNczE0cTlYRG1IMFpHWjVuSEI0THd3TnAxZDc0bFRIOXdqeS9hZzlsbVRBblln
        UEFoQ1ZuTVVZMDBWQnZHSnBpYTFTOXk4cDVvWlJLeE50SllQeFNURG9rYUlhWlJV
        bjdFN1ZDQkNyNFo4WWV1VXB0VlAzRmMzb0wvTE5LWEtsSUV5dW1oeEgrSzlDb2xh
        eHJlRUNnRTNaam96NE9hRG9RSEpRaVJ0eDZJK2c2TkVOcFptNkRNTmxOQjJQc3hs
        NGVPYVhEbW9pR1VZa2ZvdkZJZUhmUEJwRFQ3ODltcFNodm56SXdxU2d0dHhYREFj
        N01tbUkyejJPSmxrSW9CVHZ2SGIzK1V6MTNyZytzQTZaeFhPVFNTT2x3UHA0aG51
        UG53bFBVNDdRT0ozWWxuNnhOMGlGSGR4QjYvWjMxaFUwSG1HKzIralFMK2RhN0Mv
        ellXNG9FQXROU0gxQ2JWcFh4YlFnOE1ib2J3UlU1c0ZvVHVid216LzBaRGRFWWVJ
        NE5XRDIyQ3VxZ1lQbWJoQkg1T3RrRHV4V0x1bHpsVlJIY1kyeExqcHlkV2pqazhl
        cVlraHRlNDBuSmZ1MnNKMVBUeWpOeld0VkZpMzNNZmROUU5sNEtFL1M0ZVRBc092
        K0Mxdi9XVlg2K3FGeUF4Um54cGhRNnJsR0ZXQThkNG8yVm5IOEpYZklicGlPc0NB
        eWpNMDdPdklYREVmeDVtcFU0MWNqMm1GWlNZYmFSYUxjMlE4dlJWdUZQUURvcDJB
        cGtheEE2cGJrR2ZwQkZyQ1ZOKzg0Yk9WcFl5VHp1OFUxeXlTN0NpeVFVNitNYWNB
        dW5yakExMkFyVUlyM1ZqaWNINjJHeVZ5WGFwVitpbjFLY2N5aGR0U2pVMkJ0MURz
        NlAvdEZlS0c2Mjd4a21xQ0dKQTdVWnB0TVNwSWhDSzE3SEpHMGNES0RrTmxZQQpm
        NjFFc1hLTisweXhzM2UzMnJEeWR3enI3UWliRlAxY3VRVGV3SlluZkg0Ci0tLSA3
        b3VMVkFyYTk1LzRBcEFZUnlXNXBSZDVOeWg3ci9OUkk2cnhua2Jad0ZzCvDcDwAU
        3uJaHphyvn3BgweJGRHU40wUTQDgsSpxJ8fH1pcv/ZYolIk80rI6I9DOOuv7ipYz
        4NwdQJtcDwhAOtE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T22:58:04Z"
  mac: ENC[AES256_GCM,data:3IWnS2L6qrh0GfxmIeUk3pdbE8c+ILtU22TBdp9bq+4fl8ADdlSUAbYPdbAAoZR9M/nGYFys+X+vciZQExLXEh12H/0J3s8qKEgj7eRdKv7VRzKxv4OWs3A0Dpk13RKZUUbbqm3iY4UpX4YKQD/xSR2Zp6Ar2re+Qlo6VgKbL+s=,iv:2LAPxAPFB+hvWXtIqFjgzAS8gF7logcnRWfKq3K1bRM=,tag:gJH7iEVoGJ/RtcWXfrQjTQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
