apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8uC7VLlvZB8o0FRlQR68dgwGcqphNJF2Yd76wBg/1rkKNFPBXULgmKsfRAHZHKPcdWLhgWw=,iv:yxddMEoAwY3VOB1ikmHy8Qz/VpS71Ne055I3Ps6EPEY=,tag:3qQpdgQqVn7VRDBozB0bsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEVtdzNQS0lx
        WXhnZ29IdUZMZXVoeGhlTS9BblBzdW9jaUgzWjZTQVozdTZNMERJaG5jdXlpRDcv
        WU5CdSszUldFSnNTKzh1Y1RnWmZMdjJXL2hLc0cvTm1rWGNNajBRUzlybkIzMFBr
        cXdnTXhvZU1FaVpMQm5BTnIrdFZPY0w1ZU8rNDZzZUpxeVR3a2lXVmtpK2JJbVpo
        c3Y5anM0UWdBVVh0YWhXdmR0eEE3cnA1eDNRTlRHVk9UbTdEdWtpUVFab0FtSURn
        dkZ0Y2xoUmJXZmpCZFgyMTdiU2NQWU9sYWkzOFphOTNTcUh1U3Azdk5EbmhRRG1z
        RVJrb01sRHVSSXZMMmVnUEFSa0hRbE1YL0had0RGZUVudDVRUUVJK2V4WldIbnYx
        bldpYTdKbUIyTUxLT1R1QWorRXVlb3ZlK1Q1d3hjNUVESHNHMjFIek1DNTRYSUo0
        bTRqMW9YZFovM2s3Ym1yMDJ3TnVuT0ZvbUJoZkNGQVNXa3V0eTlOT2R3aGNLa3Ay
        TVZXOWVGRzQyb2tSd2xDZEFpakJ5YkRYMG03MGd4aHgwNzI3VDl1WmN5a1VKWHNt
        Q3VSMDYrQ2NqdUFtRXd4UjNvbWlQdUlROGlIc0JqLytLbUE0RklJYllvSTNTQ2dG
        T1pBVmdpMG9VRzlPYnZVaXJyOUxWVU1zYk1GVHhtVTZvS3hQNmhQSWNQZFZDUGRU
        SDRsVHNzOWN5NFZxSEdLM0JmU1BGZzFZaldzVGlVYkZHZVZuN1dYWHIxUEk1K1BY
        eGcyalRoaVU2YnRHd3FMODZmVlJDaVVBdFpLWDR3YSsrazBzZjByWGNDNVA5REl2
        RS9rVTFHclM3aHdFSEcvY28ySSs3T1NSU2hxTS85NFp3MlJWekxGQWtTaEZxbXJI
        b1ZLYzN3K3NQcTdPOWYzTzlFbmJKWTJwcGNCWTNCenk2NkR5bEsxZzlhMG5vNXF1
        dlZNOCtjWXNWL0pJZERJTnZIaTN3OEo0clhCd1F0eU5pNS80U3RyT0tkcGlMR1Nj
        c2Q4QUx3WDdINlRuK2tWMEU1eW5GcWkvZXQ1RkxQZnpWbHIyanlpcE1MWDNVQi9O
        d0xQTXZNNW56NEVNTDZpdE9tSVhhZGtPeU8wM3VtdG1Rc1RYQVdNUUlMcjcyR1hR
        SXI1VE9wM2FlQ0E3cHVIMlJlVER2WHlHbm5EZ3k2WU5IR3JneURMSFZiUTRuTldQ
        eXlINmExVzViT2MyaWpZZlFmZnBlaUlJK01ZeGJGdkN3ZCtvQ0VzZTFnNTVEdUds
        VHpvbUp0SmRhMFpXbGl2MDJTM2JtRTFHM1o1MmtEb0VNUEg1NXRBZ0daRDdvd1hK
        c2RleVpDNkdJb3AxSlpWeHdZLzZkcVpLMHRmQy9MVU8rSXR3Y2tFM0JsWVNFb2po
        T1pDTWpnalJTVTV3OFN3bjg1MGdOdnVQT1phejBhNmluUEJ0cWtGeHJUcEFBTS90
        ZGV4cHp6RWJlUW53QithVG1nWnVNZzBzYXMvR1A2WnloKzJHdCtnS25yUXh0M2lJ
        Q01hS3hTUzJFT1ZSR2dCMlkwMWVoUk1KUnRBaklaeEIySXZvNFJCZm9FbGc3VVNI
        Mm9uTjlJMlYxRkhTZStrQTAxMlIzVUd5UUFJZE44akY3Nnd5bkJyekVNMnMvWVBp
        V00reDNaTzRYZmRuNGU3NDNrd3NGc1E3K3BZK244ZFFpMXd4MkFJU1JKMk9FTm1u
        cnREUGswdHdmWTVZb0Ezcmw4eDNBa1FmS0JHdTlpM001dzN3ZnZIYURvbGpFMkI3
        dlhReGF1UndXMkFCUC9yVHpLRlE4UnI5eEpReVBVTHhWdGkvUzhXV29KcUYxUGdL
        bkVnT3FvODdMOS92Zlp3a2F4NWtzUS9uUDdkN1U2TDNWZXJiOUZpbE9NK0RIeVZD
        czkzT1M2WVpYTjA0V3plMWt6cWxtOGJyd00vY01USTZtMkxXQUh3bFBtNjFMUQpr
        b1daUDFUNE4vVy9PckRka01jRkdzbmJuU3JOV2VuWnU5NHJDNlZVODBzCi0tLSBn
        SE5rL1RUY1dGSGpkaEl3SStxVzZCRmpDZU9mcTI4UGZvMTJYOFcyR0ZVCnTyN4ZP
        b7hff3gmh9AFVC7sHRmodSRKVnxhSB6WEUhUrTAJYMqvvqAhCG1MM8DUOsOVdCrS
        CeD6VzLKoxnH7f0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13jxpm3h80sesw8g8jqc07svgd7ch9rh296hhdfnengl7ne955prqwzg3w36q2egy5qmnx2mzalvs02ap962gtgrxxjafnfzydkfg8mqvjrrr55eec9kku5zqffdsqs8rg8etkf3ar3qhcucr6yyear6n3tvqpf43g95du7pzy86f4ep6zqeu2pq27gupfxjzuhqqsuazh54k8zx4774jk3cd0538jk2fx09aqpq6sf34czmq6vykacd4d858gq3yh22u0pv2c36yl6e85egyseee2fzm6cvaquv9quknjtrr3gd279jqlgjkj7gjhfynty560nmdkpsgu5va36pudzgvw4cdpjswjq5dle4x6t9s2gpx53s2ftqzw7f6scf3667fkvcmq6d5qj9sw65ktvuhw8tszr0rdan50th74zwkmam0gjry2d7m9jwp5m44q5reed6nuhzpe3vu3hu228lmepyj2vz87g7guspnk76wqp42zakxuzmxxz3s7vhuyajsdw845k53eqcypwgnqet42qqkxne6w9kr5yrxdwvpk0dcsczjrr3f49p2mwfelwcu3q2q2n7pckck328xld964ug2duy6r5fhspqn8gkv8ryk9f6rkkue8ffccvudhdvzkgcstwtry9vht6fccfzxgqy0je9au64tv6gkc2nmngad7ffqegjskwuv7kjvpdckfqgghpefywg7jv4clyqf598uv5c2upadhd28j4x8ym94fypuht6r65xr9zwfaqnngjysjdwjgzfe9ry7hvchpff40qrsy0dhwu3tlxggf7rhmfcnjdmvqutjvp3rd8ydmdwrefjm2knzgv5xppczwvmt67390rsvugry3qfrc8kqn09aqmpylq5upfhst75anv9wsc97mlznlcmsntlt9dndsjfskkz75kapyack4wt8nwev90jv4ppy4atnanzsptxueytmrxtnyxunjeeak2j3py65ygazjn2u295pfy6mfw7tttrs8ftwsywtlfwt2a4ynhx9ce9q936lckd35x7he0xpu9segvlcesj2sd4fr88lcavzj65cejtnv9z2dpuswk5rqcj3mg6hgxsedczw2zwa4gvfljkdah4876thchtd5e39ueuc5emvwadjhvjer6lfk9y92pzzhvzc403xtxf4fa75xdkxyzveja6wz6phtsk8287gvsqszdtevq6qmd55h5efvckf2aqtj9hvpgm2mj4z7dkpkhndg92auj053afwj0vnp0dpp2xsyhhsedum4sac2gtxsa4xvnrak6ryldqfuqfd5hkvtk5n8lgkwtdxqx0wqky3yh5grwappefvqc40rgmjadevknz8fqgkry5sq6cpg72syvtes553d2t3ymafvs6xgygw2vauguq8eyahwufzwc0hsmx9fkgwjdnk376gp0rev26lyu0pc6qtzmgyeak4z4re2cp7pqydpxek8239ewdp4ss0rnvetvx8thxthvmt92mxzwumxv7cc7jptxteue5mdysqfvfkc4p8260y6cptrpjv4mvrju2jygr527tg74g5xsy6xyscnqz7x7v6f2ahx55tacv68sh6sllrjqtezc94rf3r06v3u65y2c8hyx7hcutszzdulhsgycf6yq6dx58lzvufkaaykvv855dg0jkuqyewc9t4wfdn34w89gh607cggehhgyw69cd5dms5509fhwm3vd54uasr2tpxf248pzg3v4u2wd4h8d4crcqu2wvclm7kr900s742h3d0v9xdfyc40rfpyfuafd7myc5s3fuljsgku2sfrt9lgqjyja2v89h2h9yq2le8g9thpte7qtlf7hknstaw5mwwstavvlvezcun9vxzzjytkuw4s8rssa6x5mrdmpvy7jtvrlms0yxm0fcje0gwnhshtsp8uxed
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T02:07:07Z"
  mac: ENC[AES256_GCM,data:DuWCJXvTth1DfMie0Qv3p2SZQtbnYCJZl7NUJlYQch4yjuhon7FK4psKPh+RxRAlyLWwaTKaupG1NOMwgQCwVABxQ+MBYke4RtFBWjXILf2rnfpqJA8rt8yVQ6N6/h5rqW9v9nepiM25229vB9Ktxh2OlKQAv7wwIbriCVuZSJQ=,iv:TmLP1Z/rqdyV5HtEEBd2zHePeYrS6Pt14CNGkhL/YHk=,tag:o3uLDUldC26okhJCyPkaxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
