# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudnative-pg
  path: ./kubernetes/apps/database/cloudnative-pg/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 24h
  retryInterval: 1m
---
# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: database
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: external-secrets
      namespace: external-secrets
    - name: miroir-config
      namespace: miroir-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgres
      namespace: database
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudnative-pg-cluster
  path: ./kubernetes/apps/database/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 24h
  retryInterval: 1m
