apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi-driver
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: ceph-csi-driver
  interval: 1h
  path: ./kubernetes/apps/rook-ceph/ceph-csi-driver/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rook-ceph
  timeout: 5m
  wait: false
